### ISSUE TITLE
Currently it is Impossible to get Refresh Token to revoke it

### ISSUE THREAD

**Issue by mikhail-slauth** [auth0/auth0-spa-js#1013]
### Currently it is Impossible to get current Refresh Token to revoke it

> I need to revoke Refresh Token on log out (see https://auth0.com/docs/secure/tokens/refresh-tokens/revoke-refresh-tokens), but this is not possible, because I can't get it anyhow via current api. For some reasons `refresh_token` is omitted from `getAccessTokenSilently` method (see https://github.com/auth0/auth0-spa-js/blob/master/src/global.ts#L641).

### Possible solutions

> Implement dedicated method `revokeRefreshToken` which will revoke current refresh token according to doc in  https://auth0.com/docs/secure/tokens/refresh-tokens/revoke-refresh-tokens

**Comment by frederikprijck** [comment]
Thank you for reaching out!

This is a fair request, as we do not offer a way for you to revoke refresh tokens. This is something we would want to look into and see if and how we can improve to acomodate for this.

However, I wanted to give a small overview of the complexity we are dealing with, based on [the documentation you linked to](https://auth0.com/docs/secure/tokens/refresh-tokens/revoke-refresh-tokens):

**Grants**
Auth0 uses the concept of grants, without going too deep into this, in the context of Refresh Tokens, it's basically a way to group certain refresh tokens together. While a user is using your application, which is using our SDK, you might end up with having used different refresh tokens, possible belonging to the same or even different grants.

Basically; Whenever the exchange of a refresh token fails, our SDK falls back to using iframe's. When this fallback is succesfull, it will result in a new refresh token that belong to a different grant.

**Revoking the Grant**
As can be seen in our documentation, you can decide to revoke the entire grant for a refresh token.

However; as mentioned above we might have been using refresh tokens of different grants, which means that we can only revoke 1 grant, the one for the current refresh token. Which could mean some refresh tokens, and grants that have been used throughout the duration of your application are not revoked. Typically, rotating the refresh tokens as well as its expiration should help you protect here, but when talking about revocation, these are also important to consider.

I will raise this within our team to have a conversation about this, and if/how we could best offer a solution for this.

**Comment by ewanharris** [comment]
Hey @mikhail-slauth, thanks again for opening this issue.

We’ve investigated the feasibility of supporting refresh token revocation directly in this SDK and have decided that, for now, we won’t implement an API for it given that there is a solution for this already (outlined below), and this SDKs support for multiple audiences and scopes there could be some confusion around the API.

For now, our recommendation would be that if a refresh token revocation is required to call `getTokenSilently({ ignoreCache: true })`. Due to the SDK using [rotating refresh tokens](https://auth0.com/docs/secure/tokens/refresh-tokens/refresh-token-rotation), this will invalidate the previous refresh token ensuring it cannot be used again.

We will definitely continue to consider this request in future however.

**Comment by MatthewEppelsheimer** [comment]
> For now, our recommendation would be that if a refresh token revocation is required to call getTokenSilently({ ignoreCache: true }). Combined with the use of [rotating refresh tokens](https://auth0.com/docs/secure/tokens/refresh-tokens/refresh-token-rotation), this will invalidate the previous refresh token ensuring it cannot be used again.

AFAICT, this recommendation revokes the previous refresh token but sends the **new**, valid refresh token to the browser, vulnerable to an attacker intercepting network traffic.
