### ISSUE TITLE
Tokens not persisting in 2.0.0, working in 1.22.5

### ISSUE THREAD

**Issue by ZeeStorm** [auth0/auth0-spa-js#1049]
### Describe the problem

Presently using latest ^1 (1.22.5 at the time of this writing) in a Vite + Typescript + React application. Upgraded application to 2.0.0, followed migration guide and users are no longer able to retain sessions (immediately logged out upon refreshing page).
When we initially implemented Auth0, we relied on localStorage, but our security team required us to remove that (however 1.x still seemed to work without the localStorage setup). We cannot go back to using localStorage for 2.0.0, however I suspect that implementation likely works.

### What was the expected behavior?

Users should stay logged in after refresh the page like they do in 1.x

### Reproduction

Here's our 1.22.5 setup
Init at start of app:
```
  const auth0Client = new Auth0Client({
    audience: AUTH_AUDIENCE,
    domain: AUTH_DOMAIN,
    client_id: AUTH_CLIENT_ID,
    redirect_uri: `${window.location.origin}/login`,
    // we use MFA, social logins and enterprise connections
    // need refresh tokens
    useRefreshTokens: true,
  });

  try {
    const token = await auth0Client.getTokenSilently();
    console.log('token', token);

    const isAuthenticated = await auth0Client.isAuthenticated();
    console.log('isAuth', isAuthenticated);
  } catch (e) {
    console.error(e);
  }
```
As expected, initial load throws on getTokenSilently (missing refresh token, because user isn't logged in), so we go to login flow

Login flow:
```
  const queryParams = new URLSearchParams(location.search);
  const code = queryParams.get('code');
  const state = queryParams.get('state');
  if (code && state) {
    try {
      const result = await auth0Client.handleRedirectCallback();

      console.log('result', result); // all good here

      const isAuthed = await auth0Client.isAuthenticated();
      console.log('isAuthed', isAuthed); // returns true

      // everything is good, document redirect instead of react router to simulate user page refresh
      document.location = '/welcome'; // normally takes redirect
    } catch (e) {
      console.log('error', e.message);
    }
  } else {
    auth0Client.loginWithRedirect({
      redirect_uri: `${window.location.origin}/login`,
    });
  }
```

All works correctly. User is logged in, refresh tokens work, I go about my business.
The page properly reports my token and isAuthenticated = true
I can refresh the page over and over again, always works

Now taking the exact same project, simply removing the 1.x package, installing 2.0, following the migration guide for the slight changes in config. I also tested other formats, such as using `createAuth0Client` without getTokenSilently or checkSession.
```
  const auth0Client = new Auth0Client({
    domain: AUTH_DOMAIN,
    clientId: AUTH_CLIENT_ID,
    authorizationParams: {
      audience: AUTH_AUDIENCE,
      redirect_uri: `${window.location.origin}/login`,
    },
    // we use organizations, MFA, social logins and enterprise connections
    // need refresh tokens
    useRefreshTokens: true,
  });

  try {
    const token = await auth0Client.getTokenSilently();
    console.log('token', token);

    // also tried without getTokenSilently with just:
    // await auth0Client.checkSession();
    // no errors are thrown and the next line executes, but isAuth returns false

    const isAuthenticated = await auth0Client.isAuthenticated();
    console.log('isAuth', isAuthenticated);
  } catch (e) {
    console.error(e);
  }
```

The only change for login flow was the loginWithRedirect params to use the authorizationParams:
```
    auth0Client.loginWithRedirect({
      authorizationParams: {
        audience: AUTH_AUDIENCE, // tried with and without
        redirect_uri: `${window.location.origin}/login`,
      },
    });
```

During the login callback, we properly receive a result, isAuth=true, so that appears to be working, however on immediate next page load the refresh error comes back up immedaitely:
`Error: Missing Refresh Token (audience: 'X', scope: 'openid profile email offline_access')`

I also tried the new `createAuth0Client`, which is significantly simpler, however it continues to say not authenticated:
```
  try {
    const auth0Client = await createAuth0Client({
      domain: AUTH_DOMAIN,
      clientId: AUTH_CLIENT_ID,
      authorizationParams: {
        audience: AUTH_AUDIENCE,
        redirect_uri: `${window.location.origin}/login`,
      },
      // we use organizations, MFA, social logins and enterprise connections
      // need refresh tokens
      useRefreshTokens: true,
    });

    const isAuthenticated = await auth0Client.isAuthenticated();
    console.log('isAuth', isAuthenticated); // always false
  } catch (e) {
    console.error(e); // no errors are thrown at all during this implementation
  }
```

I wanted to ensure I spent as much time as possible ruling out any issues on our side before raising a bug here, so I spent quite a bit of time stepping through the code during auth.
The only thing I found weird was the cache manager was always empty, but cache mode did show it was on. The cookies for localhost also did have a valid "is authenticated" cookie: `auth0.<clientId>.is.authenticated` = true

**Can the behavior be reproduced using the [SPA SDK Playground](https://github.com/auth0/auth0-spa-js/blob/master/DEVELOPMENT.md#the-sdk-playground)?**

I was not able to get this working properly, but the code above does reproduce it in the most simplest form I can provide

### Environment

- **Version of `auth0-spa-js` used:**
  1.22.5 and 2.0.0
- **Which browsers have you tested in?**
  MacOS 12.6.1, Chrome v107.0.5304.87
- **Which framework are you using, if applicable (Angular, React, etc):**
  React running under Vite with Typescript
- **Other modules/plugins/libraries that might be involved:**
  If it makes a difference, we are using esbuild's global polyfills due to a package that relies on buffer:
  ```
    import { NodeGlobalsPolyfillPlugin } from '@esbuild-plugins/node-globals-polyfill';
    ...
      plugins: [
        NodeGlobalsPolyfillPlugin({
          buffer: true,
        }),
      ],
    ...
  ```
  We are also utilizing SSL locally (https://localhost) with a valid certificate

**Comment by frederikprijck** [comment]
Thanks for reaching out.

What I think is happening is the fact that we flipped the default value for `useRefreshTokensFallback`, see: https://github.com/auth0/auth0-spa-js/blob/master/MIGRATION_GUIDE.md#no-more-iframe-fallback-by-default-when-using-refresh-tokens

You can either set this back to true, or ensure you call `loginWithRedirect` yourself when loading the page. The reason for this is, because you are using in-memory, refreshing the page loses all user information. This means that, we need to contact auth0 to see if the user is authenticated, you can do this either by calling `loginWithRedirect`, or by relying on the fallback.

Would that help?

**Comment by ZeeStorm** [comment]
Thanks for the quick response @frederikprijck. I saw that comment but didn't quite understand it, I apologize for that. I also reviewed some of the more lengthy information regarding the original implementation on [Auth0's site](https://auth0.com/docs/secure/tokens/refresh-tokens/use-refresh-token-rotation#enable-userefreshtokens). Is there any concern that Chrome will be moving to disabling the iframe fallback in the near future? I believe it's written somewhere that Safari and Incognito Chrome already fail with this method, is that correct?

Outside of the obvious issue that all new pages would require the user to re-authenticate, our SPA purposely opens (most) links in new tabs due to our customer's behaviors and how they use our app, which means we are trying to ensure the most streamlined experience on their side. Many of our customer's IT requirements also do not allow them to "Keep me logged in" (which is also why we had to remove using local storage cache).

Is there any other documentation around Auth0's refresh tokens that could offer a better solution to NOT use the Iframes fallback? I understand circumstances aren't always a 1-size fits all, but I'd like to have as much information for our security team to weigh potential pitfalls if we're hinging on the fact that 1 small update to Chrome can wholly break our authentication at the moment (which is likely stil;l true today for 1.x as you've stated).

**Comment by frederikprijck** [comment]
It's indeed true that using the iframe's fallback has issues on browsers such as Safari and Chrome Incognito, and it's very likely others will follow, as well as Chrome non-incognito.

Important to know tho, is that this is failing because of third party cookies. If you would use Custom Domains with Auth0, you would ensure there are no third party cookies at play, and the iframe fallback should work fine in browsers such as Safari and Chrome Incognito. See https://auth0.com/docs/customize/custom-domains

If Custom Domains is an option, you are safe to rely on the fallback. However, do know that also the fallback can fail if there is no active session with Auth0. So regardless, you should take into consideration that that could be the case.

> Many of our customer's IT requirements also do not allow them to "Keep me logged in" (which is also why we had to remove using local storage cache).
This does make me believe that you don't realy need refresh tokens. However, if you can't use custom domains, you do need to use them once you can't rely on the 3rd party cookies (or if support for Safari or Chrome Incognito is required today).

If Custom Domains is not an option, the fallback won't work on the mentioned browsers, and might stop working in more browsers in the future, which is also why we are starting to disable them when using refresh tokens.

To work around that without custom domains, you can implement refresh tokens. However, even when using refresh tokens with in memory caching, it's important to realise that every new tab as well as every page refresh needs the SDK to be re-initialized. This has to be done either silently, which can only happen using an iframe as there is no refresh token to use yet, or interactively by calling `loginWithRedirect`. However, with v2, we don't automatically use this iframe fallback anymore. So when you configure the SDK to use a refresh token, we won't try using an iframe and we don't have no refresh token available, so there isn't much our SDK can do. If you still wish to use the fallback here, you can enable it again by setting `useRefreshTokensFallback` to true.

By doing so, remember that it can still fail, both in browsers that block third party cookies as well as in other browsers when there is no more active session with Auth0. What you can typically do then is ask the user to interactively login again by calling loginWithRedirect. If it was a case of 3rd party cookies being blocked, the user will be logged in without further interaction. If the iframe approach failed because of no active session at Auth0, the user will be prompter for their credentials.

> Is there any other documentation around Auth0's refresh tokens that could offer a better solution to NOT use the Iframes fallback? I understand circumstances aren't always a 1-size fits all, but I'd like to have as much information for our security team to weigh potential pitfalls if we're hinging on the fact that 1 small update to Chrome can wholly break our authentication at the moment (which is likely still true today for 1.x as you've stated).

I believe these kind of questions are better suited for other departments, I would recommend reaching out to your contact at Auth0 or https://auth0.com/contact-us 

But definetly worth a read are:
- https://auth0.com/docs/secure/tokens/refresh-tokens
- https://datatracker.ietf.org/doc/html/rfc6749#section-1.5

**Comment by ZeeStorm** [comment]
Thanks for all the help @frederikprijck , I'm glad to see it's not a real issue with 2.0.0 and so I'll close my issue.

Unfortunately, refresh tokens are required since our implementation requires access tokens to last less than 5 minutes, and sessions generally last a whole work day, requiring the need to issue new access tokens throughout the day.

For what it's worth, we are using Custom Domains in production, but do not use it on our test environments. Based on your feedback, I think its worth arguing the point that for non-production environments that cannot use custom domains, the local storage mechanism is likely a pretty safe alternative. We'll test 2.0.0 using custom domains in a pseudo-production environment and see if we can find a middle ground with our security team. Thanks again!

**Comment by frederikprijck** [comment]
Our SDK can refresh access tokens without refresh tokens, that's what the iframe is doing. So if u are using custom domains in production, and not storing anything in local storage, i don't see why you would need refresh tokens in production.
