### ISSUE TITLE
Please provide more in depth examples... getTokenSilently - react...

### ISSUE THREAD

**Issue by sourcewars** [auth0/auth0-spa-js#105]
For me it"s hard to understand what's happening inside this stuff. So would be great for better examples. Everytime reloading/hot reload while developing, the app asks for login, that sucks alot. Even like described that it will automagically check with getTokenSilently is not happening. Don"t know why. But more detailed explanations would be great.

**Comment by luisrudge** [comment]
Are you by any chance logging in using a social account + using development keys for your social connections in the Auth0 dashboard?

**Comment by sourcewars** [comment]
Yep i'm using google login.

**Comment by luisrudge** [comment]
and did you setup your own google keys or are you using Auth0's development keys?

**Comment by sourcewars** [comment]
where could i set these things up?

**Comment by luisrudge** [comment]
Here's some of the limitations of using Development keys: https://auth0.com/docs/connections/social/devkeys#limitations-of-developer-keys

Here's a step-by-step guide on how to setup your google connection: https://auth0.com/docs/connections/social/google

When you use Auth0's development keys, `getTokenSilently` won't work.

**Comment by sourcewars** [comment]
Okay will test it out ! Thanks with the first feedback and i will provide infos when i'm done :)

**Comment by luisrudge** [comment]
Perfect! Let me know how it goes.

**Comment by Californian** [comment]
For others that come across this as I did, I believe my issue was related to https://github.com/auth0-samples/auth0-react-samples/issues/166, which has been incredibly confusing. I will update this comment if that is not the case.

At least, I am still getting 401 and must re-log-in every time I refresh, despite using the new universal login and having my own client id and secret set up.

Since there's no way to transfer settings to a new tenant, I'm going to have to set it all up manually again, which would have been detrimental in production and will still be incredibly tedious for my multi-testing-environment setup currently.
