### ISSUE TITLE
Total Cookie Protection breaks auth

### ISSUE THREAD

**Issue by Tenrys** [auth0/auth0-spa-js#1132]
### Checklist

- [X] The issue can be reproduced in the [auth0-spa-js sample app](https://github.com/auth0-samples/auth0-javascript-samples/tree/master/01-Login) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/auth0-spa-js#readme), [Examples](https://github.com/auth0/auth0-spa-js/blob/master/EXAMPLES.md), and [FAQ](https://github.com/auth0/auth0-spa-js/blob/master/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://auth0.com/docs/libraries/auth0-single-page-app-sdk) and [API documentation](https://auth0.github.io/auth0-spa-js/), and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-spa-js/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Firefox uses [Total Cookie Protection](https://blog.mozilla.org/en/mozilla/firefox-rolls-out-total-cookie-protection-by-default-to-all-users-worldwide/) by default nowadays, which seems to break the authentication flow, as demonstrated in this video I recorded, in the reproduction below.

Specifically, [here is the error given by Firefox](https://developer.mozilla.org/en-US/docs/Web/Privacy/Storage_Access_Policy/Errors/CookiePartitionedForeign)

Is it possible that I'm implementing the library incorrectly?

This is a problem for me as `network.cookie.cookieBehavior` defaults to 5 on Firefox, as far as I'm aware, and I don't know how else I'm meant to login... I would rather not have to use a pop-up, and I'd rather not begin working on this with a workaround if it's not going to work without any down the line.

Obviously this works fine in Chrome currently, unless you also block third-party cookies manually on there too.

### Reproduction

View this video: 
https://github.com/auth0/auth0-spa-js/assets/3979239/e00df0ca-702a-49e3-8028-2381f759f247

### auth0-spa-js version

2.1.2

### Which framework are you using (React, Angular, Vue...)?

Vue

### Framework version

3.3.4

### Which browsers have you tested in?

Chrome, Firefox

**Comment by adamjmcgrath** [comment]
Hi @Tenrys - thanks for raising this

For the purposes of this SDK, Firefox Total Cookie Protection works the same way as Safari Intelligent Tracking Prevention - which has been around for a while.

This means that Firefox joins the list of browsers, along with Safari and Brave, for which the iFrame based silent authentication will not work - because 3rd party cookies (in this instance the cookies on auth0.com that are being read from a hidden iframe) are blocked.

To make token renewal work on Firefox with Total Cookie Protection enabled, you will need to use one of the 2 workarounds described here https://auth0.com/docs/troubleshoot/authentication-issues/renew-tokens-when-using-safari#workarounds (refresh tokens or custom domains)

More info on https://auth0.com/blog/securing-single-page-applications-with-refresh-token-rotation/
