### ISSUE TITLE
`createAuth0Client` being async is awkward

### ISSUE THREAD

**Issue by jstayton** [auth0/auth0-spa-js#114]
Hey 👋 

After switching from `auth0-js` to this package, I wanted to share a piece of feedback. But before I do, let me just say: This package is _way_ simpler to use and understand. Great work!

One thing that is kind of awkward, however, is `createAuth0Client` being async. And maybe that's because of how I've integrated it into my SPA, but I don't think it's _that_ weird. Let me explain.

I call `createAuth0Client` in a standalone file that I import where needed:

```js
import createAuth0Client from '@auth0/auth0-spa-js'

export default createAuth0Client({
  // My config...
})
```

When I import it, it looks something like this:

```js
import auth0Client from './auth0_client'

async function main () {
  const auth0 = await auth0Client

  // Do something with `auth0`...
}
```

That just feels kind of weird to have to await for the client. I get that you're calling `getTokenSilently` automatically if the user is authenticated – which is great – but since most (all?) of the other `Auth0Client` functions return a `Promise` already, couldn't you re-work it to make (and cache) that call in the `constructor`, and then `await` it in the other functions?

I realize that's a major version-type change. In the interim, maybe accept an argument to `createAuth0Client` that skips the call to `getTokenSilently` and returns the client right away? Or make it easy for developers to import `Auth0Client` directly?

**Comment by luisrudge** [comment]
Thanks for the feedback! We debated this internally for a while 😅. The initial API was something like this:

```
import Auth0Client from '@auth0/auth0-spa-js'
const auth0 = new Auth0Client({...});

// ... somewhere before your app inits
async function beforeAppInit() {
  await auth0.init();
}
```

But, the results in our usability tests were kinda bad. People got very confused on why they had to call `init` in the first place. Also, the lib worked just fine without the `init`, but it would have no cache on start.

When we set our goals for this library, we wanted to be as easy as possible to get started and implement the SDK inside your SPA. One of the main goals we had was: after you create the client, you'll be 100% sure that the information you get in the methods is correct (`getUser, isAuthenticated, getTokenSilently`). In order to do that, we *have* to wait before we figure it out if you have a session or not. Since you can't have async constructors, we opted for the async creation method.

Again, thank you so much for the feedback. Keep them coming! 🎉

**Comment by fedeoo** [comment]
Hi, @luisrudge  Will you consider about this proposal? 
I have the same concern.  If it's a sync method, I could render my app earlier.
