### ISSUE TITLE
Purpose of ui_locales

### ISSUE THREAD

**Issue by Enngage** [auth0/auth0-spa-js#132]
Can you please let me know what is the idea behing the `ui_locales` parameter in login method?

```
await client.loginWithPopup({
   connection: 'someconnection',
   ui_locales: 'fr-CA'
});
```
I thought I could use this to localize the popup, but it doesn't seem to work no matter what I use.  Is localization possible with this package?

**Comment by luisrudge** [comment]
All the SDK does is send this param to the Universal Login Page. You can see how to localize that page here: https://auth0.com/docs/universal-login/i18n

**Comment by betobe** [comment]
@Enngage
I solved this issue by enabling "New Universal Login" instead of Classic. Also, my understanding is that you should use one language code from this list https://auth0.com/docs/universal-login/i18n as any other code wouldn't be valid (fr would be your case).
Then both loginWithPopup and loginWithRedirect would display login page in the desired language.
