### ISSUE TITLE
Unable to renew short-lived JWT token (getTokenSilently)

### ISSUE THREAD

**Issue by alfonmga** [auth0/auth0-spa-js#189]
Hey there,

I'm trying to renew a short-lived JWT `access_token` (30 seconds expiration) using `getTokenSilently` but when it is time to renew it throws this error:

```json
{"error": "login_required", "error_description": "Login required", "state": "…"}
```

`getTokenWithPopup` works as expected BTW.

Is this a bug?

**Comment by alfonmga** [comment]
Oh, this is not a bug.

Works as expected on Safari browser but on Chrome it doesn't, I think this is related to security policies that Chrome enforces (does not allow third-parties domains to touch `localhost` storage..etc).

Regards,
Alfon.

**Comment by benjixx** [comment]
Looks like I'm currently running into the same problem.
If this is not working in Chrome, I would consider this a bug.

@alfonmga Did you find a workaround for Chrome or did you just drop support for it (which would not be an option in my case)?

**Comment by stevehobbsdev** [comment]
@benjixx Are you getting this error after having logged in using a social provider, such as Google? If so, does the error go away when logging in using a username and password?

If the above holds true, things to check are:

* The social provider you're logging in with has been configured with real security keys, and *not* using the built-in dev keys
* OR your Universal Login configuration is set to "New" instead of classic, where using the dev keys should work

Can you let me know if any of the above fits your scenario?

**Comment by benjixx** [comment]
@stevehobbsdev I found the root cause of the issue. I was using multi auth with the Guardian app. Once I disabled multi auth, effectively using only username and password, it worked successfully.

I understand that auth0-spa-js is a new library that still needs to catch up in terms of supported features, but are there any plans to support multi auth as well, and if so is there already some kind of timeline?

**Comment by stevehobbsdev** [comment]
@benjixx I think this is more to do with the platform than the SDK itself.

I came across [this community post](https://community.auth0.com/t/unable-to-renew-token-when-mfa-is-enabled/9088/3) concerning a previous version of the SDK (but similar problem). Basically if the user opts to "remember the device for 30 days" then refreshing the token should work. I've been able to verify this myself; simply enabling multi-factor causes the token refresh to fail, unless I choose to remember the device, in which case it works. Can you verify the same?

**Comment by benjixx** [comment]
@stevehobbsdev I just tried it. Seems like checking the "Remember the device" checkbox did the trick. Thanks for the hint.
