### ISSUE TITLE
Custom Params

### ISSUE THREAD

**Issue by ChaudhryAtif** [auth0/auth0-spa-js#191]
I see this PR: https://github.com/auth0/auth0-spa-js/pull/146

How can I put this into practice? I want to customize the Universal Login UI. For example, change to username-password login, disable sign up, disable forgot password, etc.

The interface detail for [Auth0ClientOptions](https://auth0.github.io/auth0-spa-js/interfaces/auth0clientoptions.html) says:

> If you need to send custom parameters to the Authorization Server, make sure to use the original parameter name.

I tried the following, but didn't work:
```javascript
createAuth0Client({
	domain: '',
	client_id: '',
	redirect_uri: '',
	audience: '',

	autofocus: true,
	usernameStyle: 'username',
	requires_username: true,
	allowSignUp: false,
	rememberLastLogin: false,
	allowForgotPassword: false,
	sso: false
})
```

**Comment by kodezen** [comment]
@ChaudhryAtif 

I got this working for my use case (initial screen signup instead of login) by adding the keys into the Auth0ClientOptions object like you did above (step 1) and then (step 2): customizing the Universal Login page in auth0 management console with custom javascript. If you log in to auth0 and look on the left sidebar, you'll see "Universal Login." Then click "Customize Login Page" toggle to enable the ability to edit the default javascript.

This is how I got the Universal Login to open to sign up by default: 

` // Available Lock configuration options: https://auth0.com/docs/libraries/lock/v11/configuration
    var lock = new Auth0Lock(config.clientID, config.auth0Domain, {
      initialScreen: config.extraParams.initialScreen || 'login',`

**Comment by ChaudhryAtif** [comment]
@kodezen Thanks for the reply. I haven't tried it yet, but you are using Auth0Lock, whereas I am using the default/new implementation provided by auth0-spa-js (see constructor above).

Do you know if your changes will work for the updated implementation too?

**Comment by stevehobbsdev** [comment]
@ChaudhryAtif Yes, @kodezen is referring to the custom JavaScript you can write in order to configure Auth0Lock from the Auth0 management dashboard. This SDK provides no UI, it redirects the user to our Universal Login page, which in turn uses Lock.

For more information on customization of the login page, [this article](https://auth0.com/docs/universal-login/advanced-customization) should help.
