### ISSUE TITLE
IdToken and refreshToken are missing in the response

### ISSUE THREAD

**Issue by JohnnyTMD** [auth0/auth0-spa-js#201]
Altering the value of context.accessToken.scope into the rule removes from the response the id_token and refresh_token.

Code example:
`context.accessToken.scope = user.user_metadata.scopes.join(' ') + " account-onboard";`

Note that this issue is present only when using the PKCE flow.

Check the difference in the repose in the screenshots.
![Screenshot from 2019-09-04 18-16-32](https://user-images.githubusercontent.com/7419780/64268173-48569080-cf40-11e9-87bb-30469210c8c6.png)
![Screenshot from 2019-09-04 18-01-55](https://user-images.githubusercontent.com/7419780/64268174-48ef2700-cf40-11e9-8863-3f9542bffca4.png)

**Comment by stevehobbsdev** [comment]
Hi @JohnnyTMD,

This looks to be related more to the Auth0 product rather than the SDK specifically, if this is affecting the HTTP response. Would you might engaging with [our community](https://community.auth0.com/c/general) to see if your issue can be resolved there?

Feel free to attach the link to your topic here so that we may follow it.
