### ISSUE TITLE
refresh_token value

### ISSUE THREAD

**Issue by JohnnyTMD** [auth0/auth0-spa-js#204]
Hi, I'm using the getTokenSilently() method, and the response contains the access_token, id_token, refresh_token. How can I access to the refresh_token value?
![Screenshot from 2019-09-06 00-30-01](https://user-images.githubusercontent.com/7419780/64382278-f300a900-d03d-11e9-8095-25a03b62bbf6.png)

**Comment by stevehobbsdev** [comment]
Hi @JohnnyTMD,

Currently we don't expose `refresh_token` at all through the SDK. The primary purpose for that token is to fetch a new access token, which you are already able to do through the `getTokenSilently` method.

Can you tell us a bit more about your use case?

**Comment by JohnnyTMD** [comment]
@stevehobbsdev ok, I was able to get the a new token using the same method (seems like the method handles everything, like sending the refresh_token and so on...).
Now, I'm only using this refresh token once and I don't need it anymore, is there a buit in method in order to revoke the refresh_token?
I saw in the auth0 docs that I have to pass the refresh_token value if I'm going to do that by myself.
POST /oauth/revoke 
{ token: 'YOUR_REFRESH_TOKEN' }

**Comment by stevehobbsdev** [comment]
Hi @JohnnyTMD,

No we don't have such a method.

It's worth mentioning though that the SDK does not use refresh tokens at all to get you a new access token, which is why it is not exposed nor asked for (normally) during authentication. Rather, the SDK uses `prompt=none` and an iframe to silently renew the token, rather than use a refresh token.

Auth0 does not issue refresh tokens to SPAs under normal circumstances as they cannot be securely stored. I'm curious as to how and why you're receiving a refresh token in your responses. Are you sending the `offline_access` scope when you authenticate? For normal use of this SDK, you don't need to be doing that. The `getTokenSilently` method wil handle all of this for you without requiring use of a refresh token.

**Comment by JohnnyTMD** [comment]
@stevehobbsdev ok, thanks
I figured it out that the library works this way and I'm using the `getTokenSilently` method now. I was reading in the auth0 docs about the refresh_token that's why I wanted to use them to renew the token. But hopefully the task is solved now using this library.
Thanks

**Comment by stevehobbsdev** [comment]
No problem @JohnnyTMD! Please reach out if you have any further queries :)
