### ISSUE TITLE
Intermittent 401 error when calling backend

### ISSUE THREAD

**Issue by Greenbones** [auth0/auth0-spa-js#206]
I've got an app using the SPA sdk that was built off of the Angular 2 tutorial. Everything is working more or less correctly, I'm able to login, get a token and send it to my backend server without issues.

However, while I'm developing the app, I'm noticing that occasionally when I refresh the app after making changes, the sdk will:

* Redirect
* Detect that I am already authenticated
* Redirect back to my callback route
* Call my backend with the token it has retrieved
* Call fails with a 401

I have confirmed in the network tab that there is a token being sent on the call to the back end, but for whatever reason it is being rejected by the backend service.

Given how intermittent it is I'm wondering if there's some kind of race condition, but based on the code, my app isn't routed away from the callback page until it finishes handling the auth callback, so I shouldn't be calling my backend until that completes. And again, I've got a token, so things seem to be working correctly.

To add some weirdness, if I just let the app sit and it attempts to refresh its data, the subsequent requests all succeed (and the tokens on the requests are the same).

There are no logs in the console beyond the 401, so I'm not entirely sure how to proceed.

Thanks,
Jeff

**Comment by luisrudge** [comment]
What error are you getting in your backend?

**Comment by Greenbones** [comment]
I'm using Auth0's spring boot starter on my back end to validate incoming requests and it's not logging any errors. That's on info level, so I could try it on debug.

**Comment by Greenbones** [comment]
Ok with debug logging I get the following:

`org.springframework.security.authentication.BadCredentialsException: Not a valid token` and
`Caused by: com.auth0.jwt.exceptions.InvalidClaimException: The Token can't be used before Mon Sep 09 08:14:16 MDT 2019.`

So maybe this is a clock drift problem? It's weird that it's intermittent though. I also got it 5 seconds after syncing my system's clock, so not entirely sure how that's happening.

**Comment by Greenbones** [comment]
I added code to my server that adds more leeway to the not before check and I can't seem to reproduce this any more, so I think we can chock it up to clock drift. Will close.

**Comment by nyobe** [comment]
We've been running into this issue as well. It most commonly manifests when waking up from sleep:

Steps to reproduce:
- poll an api on some interval (eg 15s), using token retrieved by getTokenSilently
- put your computer to sleep and wait until the token should have expired (eg 60s) AND the polling interval has been crossed
- wake computer up, observe a 401 from the api due to expired token

I think that what is happening is that there is a race between the polling setTimeout and the cache eviction setTimeout, so occasionally getTokenSilently returns a stale token right before the token gets evicted. To mitigate this, getTokenSilently should check that the token it retrieves from cache has not expired, and if it has, fetch a new one.
