### ISSUE TITLE
Ability to pass `id_token` on initiallisation

### ISSUE THREAD

**Issue by FayP** [auth0/auth0-spa-js#210]
**Issue**
Unable to pragmatically detect the user is logged in for uses in E2E tests such as Cypress.

**Reasoning**
Following [this](https://auth0.com/blog/end-to-end-testing-with-cypress-and-auth0/) tutorial from January. Seems a little out of date as the client library doesn't accept the returned id_token/access_token instead requires a code.

To bypass this it would be useful if the param `id_token_hint` was usable to pass the token directly to `createAuth0Client`. Also, the `handleRedirectCallback` could accept the token instead of performing a request to the auth API end point here https://github.com/auth0/auth0-spa-js/blob/master/src/Auth0Client.ts#L249.

If you have a work around for this it would be much appreciated. Theres a few people struggling with this issue here: https://community.auth0.com/t/end-to-end-testing-with-cypress-and-auth0/19082/16

**Comment by luisrudge** [comment]
The tutorial should work just fine, considering it's using a different library (Auth0.js, https://github.com/danlourenco/auth0-cypress-demo/blob/base/package.json#L6).

We use cypress in this library and we actually use the 'naive' approach in that blog post and it works pretty well for us: https://github.com/auth0/auth0-spa-js/blob/master/cypress/integration/loginWithRedirect.js

Because of how PKCE works (first ask for a code, then exchange this code for the token), it's unlikely you'll be able to authenticate a user without doing the full authentication pipeline.

**Comment by luisrudge** [comment]
Also, you can send the `id_token_hint` to the Authorization Server (Auth0 in this case), but I don't think it will automatically log you in, though.

**Comment by cwmrowe** [comment]
For the benefit of others, I have managed to get this working with the following which:
1. Gets tokens from Auth0 as described in [old Auth0 article](https://auth0.com/blog/end-to-end-testing-with-cypress-and-auth0/). *You will need to make sure you app is setup as per this article for this part to work*.
2. Sets required cookies
3. Visits your apps callback page
4. Uses cypress request to intercept SPA SDK request for tokens and returns what was fetched in step 1.

```typescript
Cypress.Commands.add(
  'login',
  (username, password, appState = { target: '/' }) => {
    cy.log(`Logging in as ${username}`);
    const options = {
      method: 'POST',
      url: Cypress.env('Auth0TokenUrl'),
      body: {
        grant_type: 'password',
        username,
        password,
        audience: Cypress.env('Auth0Audience'),
        scope: 'openid profile email',
        client_id: Cypress.env('Auth0ClientId'),
        client_secret: Cypress.env('Auth0ClientSecret')
      }
    };
    cy.request(options).then(({ body }) => {
      const { access_token, expires_in, id_token } = body;

      cy.server();

      // intercept Auth0 request for token and return what we have
      cy.route({
        url: 'oauth/token',
        method: 'POST',
        response: {
          access_token,
          expires_in,
          id_token,
          token_type: 'Bearer'
        }
      });

      // Auth0 SPA SDK will check for value in cookie to get appState
      // and validate nonce (which has been removed for simplicity)
      const stateId = 'test';
      const encodedAppState = encodeURI(JSON.stringify(appState));
      cy.setCookie(
        `a0.spajs.txs.${stateId}`,
        `{%22appState%22:${encodedAppState}%2C%22scope%22:%22openid%20profile%20email%22%2C%22audience%22:%22default%22}`
      );

      const callbackUrl = `/auth/callback?code=test-code&state=${stateId}`;
      return cy.visit(callbackUrl);
    });
  }
);

declare namespace Cypress {
  interface Chainable<Subject> {
    login(
      username: string,
      password: string,
      appState?: any
    ): Chainable<Subject>;
  }
}
```

**Comment by Nadya913** [comment]
@cwmrowe Thank you for benefit, but it doesn't work for us. I got the token but when the cookie was set according  your example, the user isn't logged. How we can be sure that cookie value is correct?

**Comment by jsrhodes15** [comment]
Hey there, I noticed this issue was closed with no real solution provided. As a member of a team that relies on this library for authentication and interfacing with Auth0, I would appreciate some guidance on how to handle integration testing while following best practices. I'm happy to contribute, as our team is heavily invested in Auth0, would just need some direction.

**Comment by Taskle** [comment]
Hi all -- just a followup as someone else who has been hitting these same challenges and finally found a solution that worked...

I took what @cwmrowe provided above and proceeded a bit further as I encountered the same issues that @Nadya913 was hitting.

I was able to finally get this working by inspecting the actual cookies generated on localhost when loading the oauth screen. In the end, there were a few differences from what he provided above versus what I was observing in the live cookies.

Once I adjusted these items, I got it working... here's the working code:

```
Cypress.Commands.add(
  'login',
  (username, password, appState = {target: '/'}) => {
    cy.log(`Logging in as ${username}`);
    const options = {
      method: 'POST',
      url: Cypress.env('auth_url'),
      body: {
        grant_type: 'password',
        username: Cypress.env('auth_email'),
        password: Cypress.env('auth_password'),
        audience: Cypress.env('auth_audience'),
        scope: 'openid profile email',
        client_id: Cypress.env('auth_client_id'),
        client_secret: Cypress.env('auth_client_secret'),
      },
    };
    cy.request(options).then(({body}) => {
      const {access_token, expires_in, id_token} = body;

      cy.server();

      // intercept Auth0 request for token and return what we have
      cy.route({
        url: 'oauth/token',
        method: 'POST',
        response: {
          access_token: access_token,
          id_token: id_token,
          scope: "openid profile email",
          expires_in: expires_in,
          token_type: 'Bearer'
        }
      });

      // Auth0 SPA SDK will check for value in cookie to get appState
      // and validate nonce (which has been removed for simplicity)
      const stateId = 'test';
      cy.setCookie(
        `a0.spajs.txs.${stateId}`,
        encodeURIComponent(JSON.stringify({
          "appState": {"targetUrl": "/"},
          "scope": "openid profile email",
          "audience": Cypress.env('auth_audience'),
          "redirect_uri": "http://localhost:3000"
        }))
      );

      const callbackUrl = `/?code=test-code&state=${stateId}`;
      return cy.visit(callbackUrl);
    })
    ;
  }
);

```

Cheers,
Dave

**Comment by stevehobbsdev** [comment]
Thanks @Taskle!

**Comment by occult** [comment]
> Hi all -- just a followup as someone else who has been hitting these same challenges and finally found a solution that worked...
> 
> I took what @cwmrowe provided above and proceeded a bit further as I encountered the same issues that @Nadya913 was hitting.
> 
> I was able to finally get this working by inspecting the actual cookies generated on localhost when loading the oauth screen. In the end, there were a few differences from what he provided above versus what I was observing in the live cookies.
> 
> Once I adjusted these items, I got it working... here's the working code:
> 
> ```
> Cypress.Commands.add(
>   'login',
>   (username, password, appState = {target: '/'}) => {
>     cy.log(`Logging in as ${username}`);
>     const options = {
>       method: 'POST',
>       url: Cypress.env('auth_url'),
>       body: {
>         grant_type: 'password',
>         username: Cypress.env('auth_username'),
>         password: Cypress.env('auth_password'),
>         audience: Cypress.env('auth_audience'),
>         scope: 'openid profile email',
>         client_id: Cypress.env('auth_client_id'),
>         client_secret: Cypress.env('auth_client_secret'),
>       },
>     };
>     cy.request(options).then(({body}) => {
>       const {access_token, expires_in, id_token} = body;
> 
>       cy.server();
> 
>       // intercept Auth0 request for token and return what we have
>       cy.route({
>         url: 'oauth/token',
>         method: 'POST',
>         response: {
>           access_token: access_token,
>           id_token: id_token,
>           scope: "openid profile email",
>           expires_in: expires_in,
>           token_type: 'Bearer'
>         }
>       });
> 
>       // Auth0 SPA SDK will check for value in cookie to get appState
>       // and validate nonce (which has been removed for simplicity)
>       const stateId = 'test';
>       cy.setCookie(
>         `a0.spajs.txs.${stateId}`,
>         encodeURIComponent(JSON.stringify({
>           "appState": {"targetUrl": "/"},
>           "scope": "openid profile email",
>           "audience": Cypress.env('auth_audience'),
>           "redirect_uri": "http://localhost:3000"
>         }))
>       ).then(() => {
>         cy.visit(`/?code=test-code&state=${stateId}`);
>       });
>     });
>   }
> );
> ```
> 
> Cheers,
> Dave

Thank you for the help, this has been really hard for me recently and there are little resources :/ What is `const stateId = 'test';` used for? Can it be any random string? I didn't understand that part so well.

**Comment by Taskle** [comment]
@occult TLDR to get this to work, the state in the url params just needs to match the cookie. If you look at where it's generated in the spa library, https://github.com/auth0/auth0-spa-js/blob/master/src/Auth0Client.ts#L249 -- you'll see:
```
const stateIn = encodeState(createRandomString());
```

Also note the source code indicates:
```
Random and secure `state` and `nonce` parameters will be auto-generated.
```

So what matters is that they match. But for e2e testing, 'test' is fine.

If you still have auth issues with the above approach, it's likely because the audience param or other params aren't matching your auth0 configuration, or that you need to configure your app to have the callback url set in the auth0 spa library which then will handle the code/state params automatically.

Hope this is helpful!
Dave

**Comment by occult** [comment]
> @occult TLDR to get this to work, the state in the url params just needs to match the cookie. If you look at where it's generated in the spa library, https://github.com/auth0/auth0-spa-js/blob/master/src/Auth0Client.ts#L249 -- you'll see:
> 
> ```
> const stateIn = encodeState(createRandomString());
> ```
> 
> Also note the source code indicates:
> 
> ```
> Random and secure `state` and `nonce` parameters will be auto-generated.
> ```
> 
> So what matters is that they match. But for e2e testing, 'test' is fine.
> 
> If you still have auth issues with the above approach, it's likely because the audience param or other params aren't matching your auth0 configuration, or that you need to configure your app to have the callback url set in the auth0 spa library which then will handle the code/state params automatically.
> 
> Hope this is helpful!
> Dave

Thank you Dave for the explanation. It helped me understand the solution. I ended up using the `.env` file to make a test version of my app which mocks authentication and is faster than waiting for Auth0.

**Comment by dunson062786** [comment]
Hi @Taskle, @cwmrowe and everyone else,
Thank you for your help with this. Like @occult I've been having trouble implementing this as well. I've created a github repo https://github.com/dunson062786/login-programmatically-into-auth0-with-cypress that adds cypress to the simple react app that auth0 makes you create in their quick start. In my README.md I specify what parts that need to be configured. Currently I have 1 cypress test and it's failing. It has 1 cypress test and the test tests that the login button says 'Log out' instead of 'Log in' after logging in. I created the login command @Taskle provided. and my login_spec.js file uses it:

    describe('login', () => {
        it('should successfully log into our app', () => {
            cy.login(Cypress.env('auth_username'), Cypress.env("auth_password"))
              .then(() => {
                  // currently this fails
                 cy.get('button').contains('Log out')
              })
        })
    });

for some reason after I 

    cy.visit(`/?code=test-code&state=${stateId}`);

auth0 does not think I'm authenticated.

    const isAuthenticated = await auth0FromHook.isAuthenticated();

in line 31 of /src/react-auth0-spa.js

I've tried debugging isAuthenticated, but it's typescript so stepping through the code doesn't work the way I expect. It's weird because @auth0/auth0-spa-js has source maps in their dist folder so I thought I would be able to debug it. I have enable JavaScript source maps checked in my chrome developer tools settings too.

Anyway, please let me know if you see anything wrong with what I'm doing.

**Comment by Taskle** [comment]
@dunson062786 I recommend checking a couple things:
- on localhost, clear your localhost cookies, then go through the auth0 login manually and inspect the cookies; you should see a "a0.spajs.txs.*" cookie created on the login page. Don't login, just inspect that cookie. What's in there is indicative of what will be passed in later and should match what you pass in above.
- check the scope, audience, and redirect_uri variables set above and change them to match what you see in your code and in that cookie.
- ensure that the url you're calling in your cypress visit login() call is a url that in your SPA calls the auth0 spa library (which checks for the code/state query params). In my case, those params are check across all urls, but some folks may implement it so that only a specific url accepts those values. If you allow any url to accept it, you'll be able to land on any url after authentication.

Hope this helps!
Dave

**Comment by dunson062786** [comment]
Hi @Taskle,
Thank you so much for your prompt response!

> on localhost, clear your localhost cookies, then go through the auth0 login manually and inspect the cookies; you should see a "a0.spajs.txs.*" cookie created on the login page. Don't login, just inspect that cookie.

When I clear my localhost cookies and go through the login manually (hit the login button on localhost:3000) I get redirected to `${domain}.auth0.com/login?...` and I see these cookies:
![before login cookies](https://user-images.githubusercontent.com/1486284/73951903-4799a000-48cc-11ea-9153-7ba21220ffb4.png)


none of them say "a0.spajs.txs.*

HOWEVER,

If I hit the login button on `${domain}.auth0.com/login?...`  (I know you told me not to, but if I do) I get redirected to http://localhost:3000/?code=olqG2-3Vm_AbGOHT&state=fndJZDlURHRBdlRlc0tnMUdVWlB1MDJqTUhZTmJjSVZfVldKWVR4TndaNg%3D%3D and I break (put a debugger) on the first line of the initAuth0 function [line 22 of react-auth0-spa.ja] and I see these cookies:
![after login cookies](https://user-images.githubusercontent.com/1486284/73951032-f210c380-48ca-11ea-85be-251168a4a189.png)

which does have the "a0.spajs.txs.*" cookie (Is the * the stateId? How does Auth0 figure out what that value is? Why is it different every time?). 

> What's in there is indicative of what will be passed in later and should match what you pass in above.
> * check the scope, audience, and redirect_uri variables set above and change them to match what you see in your code and in that cookie.

when I uri-decode the value of the cookie I see:

    { 
        "nonce":"vXA9hANJU6LN6NJkwVtxMK9lMYYgZ9lC5oDM1Df7BYD",
        "code_verifier":"3B_qfpE6wzTFtoSFtoJxmeZ0QEK15ERCwZe.x3hAHDj",
        "scope":"openid profile email",
        "audience":"default",
        "redirect_uri":"http://localhost:3000"
    }


Let's call these values: nonce_value, code_verifier_value, scope_value, audience_value, and redirect_uri_value. nonce_value and code_verifier_value are different the rest are always the same.

Then if I click continue in my debugger the landing page finishes rendering and my "a0.spajs.txs.*" cookie gets replaced by a

"auth0.is.authenticated" cookie which is set to true.  Which makes sense, because logging in manually works.

From this analysis it looks like my login command is wrong. stateId is hard-coded to 'test'. Looks like this value is randomly generated somehow. But I'm not sure how. Also I may be setting the value in my cookie wrong "audience" is currently set to Cypress.env('auth_audience') which does not map to "default". Also what do I do with "nonce" and "code_verifier"? Should they be included in the cookie I send? How do I generate nonce_value and code_verifier_value?

> ensure that the url you're calling in your cypress visit login() call is a url that in your SPA calls the auth0 spa library (which checks for the code/state query params). In my case, those params are check across all urls, but some folks may implement it so that only a specific url accepts those values. If you allow any url to accept it, you'll be able to land on any url after authentication.

My cypress visit login() call is

    cy.visit(`/?code=test-code&state=${stateId}`);

since my baseUrl is http://localhost:3000 it is actually

    cy.visit(`http://localhost:3000/?code=test-code&state=${stateId}`);

http://localhost:3000 is in my list of redirect_urls I allow. and my code doesn't filter out any urls it just checks to see if they have the code and state query parameters:

    if (window.location.search.includes("code=") &&
        window.location.search.includes("state=")) {
        const { appState } = await auth0FromHook.handleRedirectCallback();
        onRedirectCallback(appState);
    }

However, appState always evaluates to undefined in my Cypress tests. Which is probably because my code and and state query parameters are hard-coded to 'test-code' and 'test' respectively.

How do I make sure they are set correctly? I just thought if the value of the state parameter in my redirect url matched the asterisks in the "a0.spajs.txs.*" cookie I would be fine.

**Comment by dunson062786** [comment]
Hi @Taskle,

I followed your directions and I figured out what I did wrong. I was setting audience to my auth_audience which is "https://${domain}/api/v2/", but it should have been set to "default". I will update my github repo in a little bit with the fix.

Thank you so much for your help!

**Comment by Taskle** [comment]
Glad you got it working!

**Comment by dunson062786** [comment]
Me too! If anyone needs a working example of logging in programmatically into Auth0 with cypress feel free to clone this repo: https://github.com/dunson062786/login-programmatically-into-auth0-with-cypress.

**Comment by aphillipo** [comment]
> I was setting audience to my auth_audience which is "https://${domain}/api/v2/", but it should have been set to "default"

How can we find out if default is correct? On your example people are saying this isn't right for them?

**Comment by Taskle** [comment]
In my case I was using a custom url as my audience and not default. Something I defined within auth0. And it's working for me as such. Admittedly it's been a while since I've looked at this, but the same code I have from above is working.

**Comment by RipTheJacker** [comment]
Additional calls in the application `getUser` or `getTokenSilently` do not seem to work this way. It appears to log me in, `handleRedirectCallback` works as expected, but `getUser` returns `null` and `getTokenSilenty` return a 'login_required' error.

**Comment by stuarth-inova** [comment]
I am having trouble getting this to work. I got my generated a0.spajs.txs.* cookie to match exactly what I see when successfully manually logging in, but I still get redirected to the login page instead of my home page. I am getting a token correctly in the first part, what could be the problem?

**Comment by ljones9142** [comment]
I am having a similar problem as stuarth-inova but not exactly the same where i am getting an error saying the ID token is missing. I can see the cookie getting set and have checked the audience etc in there are correct but it doesn't authenticate, i jest get a console log of 'ID token is required but missing'. Any ideas what could be causing this to not work?

**Comment by loremaps** [comment]
@cwmrowe and @Taskle solution worked fine for me. But I cannot make it work with Refresh Tokens. Has anyone managed this?

**Comment by ljones9142** [comment]
@RipTheJacker i am getting the same issue for getTokenSilently, have you found a solution?

**Comment by ljones9142** [comment]
Fixed the issue in my test, when we call the getTokenSilently, we pare passing scope and audience. The scope in the test was set to "openid profile email" but in our code it was "openid profile". It seems to add "email" in the browser so we have added it to the getTokenSilently and this has resolved the problem

**Comment by stevehobbsdev** [comment]
@ljones9142 Currently the SDK always sets default scopes of `openid profile email` regardless of your scope setting. However, we're working on a way you can specify [default scopes](https://github.com/auth0/auth0-spa-js/pull/435) which may make it more configurable for you.

**Comment by marcenacp** [comment]
Hi everyone, I struggle to stub the authentication process to make auth0-spa-js work with Cypress.

1. I successfully send a `grant_type` request that gives me a viable access token.
2. I successfully set the cookie `a0.spajs.txs.${stateId}` (similar to the one I have when inspecting auth0 cookie in a normal setup).
3. But, when I hit the callback `/?code=test-code&state=${stateId}`, the cookie gets deleted and I am sent back to the login popup.

**Comment by stevehobbsdev** [comment]
The cookie is deleted by the SDK as part of the transaction completion stage as it's no longer needed.

**Comment by marcenacp** [comment]
@stevehobbsdev Thanks for the explanation. Why am I no longer authenticated as soon as I `cy.visit` another page?

On localhost, whenever I refresh the page, auth0 automatically login without prompting the popup a second time.

**Comment by TomaszWaszczyk** [comment]
Look at the plugin: https://github.com/lirantal/cypress-social-logins/

**Comment by NikoKodzhabashev** [comment]
Hmm...I logged in successfully but if I try to redirect to another page after that I am getting 503 ( Service Unavailable ). Do you have any ideas about what is going on? Than you in advance

**Comment by arthurorbica** [comment]
I cannot get the recommended solution to work with v1.12.0 - see this issue https://github.com/dunson062786/login-programmatically-into-auth0-with-cypress/issues/6

**Comment by matinfo** [comment]
Perso finally I use the new possibility to store in localStorage the token and now my cypress test work.

```
Cypress.Commands.add(
  "login",
  (targetUrl = "/") => {

    // cy.log("Logout first (if logged)");
    // cy.getCookie("auth0.is.authenticated").then(($cookie) => {
    //  if ($cookie === "true") {
    //    cy.get('[data-cy="menu-user"]').click().wait(500)
    //      .get('ul[role="menu"]').find("li").contains("Logout").click();
    //  }
    // });

    const client_id = Cypress.env("auth_client_id");
    const client_secret = Cypress.env("auth_client_secret");
    const audience = Cypress.env("auth_audience");
    const username = Cypress.env("auth_username");
    const password = Cypress.env("auth_password");
    const scope = "openid profile email";

    cy.log(`Logging in as ${Cypress.env("auth_username")}`);

    const options = {
      method: "POST",
      url: Cypress.env("auth_url"),
      form: true,
      body: {
        grant_type: "password",
        username,
        password,
        audience,
        client_id,
        client_secret,
        scope,
      },
    };

    cy.request(options).then(({ body }) => {
      const { access_token, expires_in, id_token } = body;
      const key = `@@auth0spajs@@::${client_id}::${audience}::${scope}`;
      const auth0Cache = {
        body: {
          client_id,
          access_token,
          id_token,
          scope,
          expires_in,
          decodedToken: {
            user: jwt_decode(id_token),
          },
        },
        expiresAt: Math.floor(Date.now() / 1000) + expires_in,
      };
      cy.setLocalStorage(key, JSON.stringify(auth0Cache));
      cy.visit(targetUrl);
    });
  },
);
```

**Comment by arthurmcgregor** [comment]
Thanks @matinfo!

Still not working for anyone else? Remember to set `cacheLocation: 'localstorage'`! That tripped me up initially...

**Comment by andreasvirkus** [comment]
So auth0 now has an official option to store the user's access token in local storage? :/

**Comment by jrozbicki** [comment]
@loremaps probably not relevant anymore, but 
* adding `offline_access` (`const scope = "openid profile email offline_access"`) in scope did the trick with Refresh Tokens, somehow I found this info here: https://auth0.com/docs/api/authentication?javascript#authorization-code-flow-with-pkce under Remarks section:

```
Include offline_access to the scope request parameter to get a Refresh Token from POST /oauth/token. Make sure that the Allow Offline Access field is enabled in the API Settings.
```


* it was important to mirror exactly what normal localstorage key holds, especially `decodedToken` value, because `getIdTokenClaims` (which I'm using to extract jwt token for Authorization header) would return undefined otherwise.

* audience in localstorage key had to be `default` instead of `https://domain.eu.auth0.com/api/v2/` value passed to `https://domain.eu.auth0.com/oauth/token` request

My exact cypress login command:

```
import "cypress-localstorage-commands";
import jwt_decode from "jwt-decode";

Cypress.Commands.add(
  "login",
  ({
    username = Cypress.env("auth_username"),
    password = Cypress.env("auth_password"),
    targetUrl = "/dashboard"
  } = {}) => {
    const client_id = Cypress.env("auth_client_id");
    const client_secret = Cypress.env("auth_client_secret");
    const audience = Cypress.env("auth_audience");
    const scope = "openid profile email offline_access"; // important to include offline_access when using Refresh Tokens

    cy.log(`Logging in as ${username}`);

    const options = {
      method: "POST",
      url: Cypress.env("auth_url"),
      form: true,
      body: {
        grant_type: "password",
        username,
        password,
        audience,
        client_id,
        client_secret,
        scope
      }
    };

    cy.request(options).then(({ body }) => {
      const { access_token, expires_in, id_token } = body;
      const [header, payload, signature] = id_token.split(".");
      const tokenData = jwt_decode(id_token);
      const tokenDataHeader = jwt_decode(id_token, { header: true });
      const key = `@@auth0spajs@@::${client_id}::default::${scope}`;
      const auth0Cache = {
        body: {
          client_id,
          access_token,
          id_token,
          scope,
          expires_in,
          decodedToken: {
            encoded: { header, payload, signature },
            header: tokenDataHeader,
            // below is returned by getIdTokenClaims
            claims: { 
              __raw: id_token, 
              ...tokenData
            },
            user: tokenData
          }
        },
        expiresAt: Math.floor(Date.now() / 1000) + expires_in
      };
      cy.setLocalStorage(key, JSON.stringify(auth0Cache));
      cy.visit(targetUrl);
    });
  }
);
```

**Comment by frederikprijck** [comment]
Thanks for the explanation @jrozbicki, always helpful to provide such information for people in the future. 
I wanted to chime in to drop this link in this issue as well, as I think it can be valuable for anyone looking to integrate the two: https://sandrino.dev/blog/writing-cypress-e2e-tests-with-auth0

That said, we are aware of the fact that our official documentation regarding Cypress is lacking and are working with the Cypress team to improve this for the future.

**Comment by urosgruber** [comment]
I was able to use this in our test but just half way. Whenever we use click out to next subpage user is not logged in anymore. Is this expected or issue with this approach?
