### ISSUE TITLE
getUniqueScopes forces DEFAULT_SCOPES to be in scope

### ISSUE THREAD

**Issue by 7opf** [auth0/auth0-spa-js#228]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

> Provide a clear and concise description of the issue, including what you expected to happen.

The `getUniqueScopes` function in `util.ts` merges an array of scope strings into a single, de-duplicated scope string, however it's always called with `Auth0Client.DEFAULT_SCOPE` as an argument which means the "default" scopes are always included in the resulting scope string, even if they are not desired by the client. Open id only specifies `openid` to be required, `profile` and `email` are optional. I may be misunderstanding something, but thought this might be a mistake?

### Reproduction

> Detail the steps taken to reproduce this error, what was expected, and whether this issue can be reproduced consistently or if it is intermittent.
>
> Where applicable, please include:
>
> - Code sample to reproduce the issue
> - Log files (redact/remove sensitive information)
> - Application settings (redact/remove sensitive information)
> - Screenshots

No matter what scope string is provided in the configuration for Auth0Client, the default scopes are always requested.

### Environment

> Please provide the following:

- **Version of this library used:** 1.2.4
- **Version of the platform or framework used, if applicable:** Angular 7.2.15
- **Other relevant versions (language, server software, OS, browser):** Any
- **Other modules/plugins/libraries that might be involved:** N/A

**Comment by luisrudge** [comment]
You're spot on. We'll always ask for `openid email profile` because it's what most apps need to work.

**Comment by 7opf** [comment]
@luisrudge I'm confused, will you address the issue in a future release? In my app, I don't want to request email and profile, for example.

**Comment by stevehobbsdev** [comment]
@7opf Could you elaborate on the issue you're facing, and why requesting `openid email profile` is proving to be an issue? Unfortunately it wasn't clear from your issue report above.

**Comment by 7opf** [comment]
@stevehobbsdev Given the below configuration, I would expect that my application requests two scopes from the auth server (`openid http://some-namespaced-scope/scopeName`):
```
  // Auth0 application configuration
  config = {
    domain: environment.auth.domain,
    client_id: environment.auth.client_id,
    audience: environment.auth.audience,
    redirect_uri: `${window.location.origin}/callback`,
    scope: 'openid http://some-namespaced-scope/scopeName'
  };
```
But instead, the DEFAULT_SCOPES are always added to the requested scopes even though `profile` and `email` are optional in the spec. 

Expected: `openid http://some-namespaced-scope/scopeName` 
Actual: `openid http://some-namespaced-scope/scopeName profile email`

**Comment by luisrudge** [comment]
@7opf Can you clarify what issues (if any) are you seeing when requesting extra scopes?

I think giving you a bit more context on why we always send `openid profile email` also helps: this SDK is supposed to be very opinionated on how it is used. That's why we built the public API the way it is today. By always requesting `openid profile email`,  we facilitate the addition of new scopes when needed, but still having sensible defaults for the general use case. We believe that requesting `openid profile email` makes it easier to get all the user information most of the developers need to get when authentication a user. Without sending the defaults, we'd likely have to remove the default altogether because the experience of adding a new scope would be super bad.

**Comment by 7opf** [comment]
That's fair enough, but for my use case I don't want users to think that the application needs access to profile and email scopes when it doesn't actually need it. If it's a default, shouldn't app developers be able to override it?

**Comment by luisrudge** [comment]
@7opf does that mean your app doesn't display any information of the user? Something like `Welcome, {user.name}`, or the email of the logged in user etc?

**Comment by 7opf** [comment]
It does, but it doesn't get it using profile scopes. I'm following guidance from http://www.hl7.org/fhir/smart-app-launch/scopes-and-launch-context/index.html#scopes-for-requesting-identity-data

**Comment by luisrudge** [comment]
@7opf sorry if I'm missing something obvious, but this piece of text says you should ask for `openid profile` or `openid fhirUser` to get an id_token with the user data. That's exactly what we do (with the addition of the `email` scope, right?

**Comment by 7opf** [comment]
Yes, but profile is being deprecated. I understand that theres an ease of use gain for most developers using this library, but since those scopes are optional, shouldn't there be a way to remove these scopes from the default list for those developers that don't want their apps to request those scopes?

**Comment by luisrudge** [comment]
@7opf just so it's clear: are you using Auth0 with another OIDC provider? Because `profile` is not being deprecated at Auth0, but maybe it is being deprecated by your 3rd party Identity Provider. Did I get this right?

My main concern with allowing to override the defaults is that the experience might break as the developer starts to dig deeper into their integration. Imagine this scenario:

- dev starts to integrate auth0-spa-js into their app for authentication (no APIs yet)
- we provide openid profile email as default, so that's what they get without adding any code
- dev finishes the integration and uses `getUser` to get the user information (name, email etc)
- now they want to use their APIs
- so they use `scope: ‘https://myapi.com/do-something’

If this overrides the default scope, now other parts of their code will break because the default is not there anymore.

So, the only way we can possibly integrate something like that into our SDK would be to do it something like this:

```
const auth0 = await createAuth0Client({
  client_id: 'cid',
  domain: 'domain.auth0.com',
  advancedOptions: {
    defaultScope: 'openid'
  }
})
```

Now, I'm not saying we will do that, but that's something that I can start an internal discussion about it. Would you say that this is an acceptable solution for your problem?

**Comment by 7opf** [comment]
It's being deprecated by the group that defines the scopes to use in the context of the data standard they are used in (FHIR). So not a 3rd party oidc provider. Your proposal would solve my use case as I'd implement my own getUser anyway. Perhaps it would make sense to be able to override this function too?

**Comment by luisrudge** [comment]
@7opf Would you mind sharing with me how your app is setup to work with Auth0? I'm interested in this scenario to see if we can do more for this use case, but I need to fully understand it to make sure we're on the same page. Thank you so much for your patience!

**Comment by 7opf** [comment]
We can talk over a phone call? is there a slack/discord/telco I can join?

**Comment by godhar** [comment]
Has this solution been implemented? I would sure like if it was. I am using a custom authorization server, where I need to use my own scopes.

**Comment by stevehobbsdev** [comment]
@godhar It has not been implemented so far to date. Can you tell me more about your use case?

**Comment by godhar** [comment]
@stevehobbsdev I have been given a django oauth2 server with pkce implementation. No oidc layer, no no SPA credentials to send to the server. I have an /authorize and /token endpoint, but I need to handle all the rest as well, silent refresh (I think), oauth iframe flow and tokens. Every library I had tried has this oidc layer that I do not need. 

SPA - oauthserver/authorize + pkce   ----> server.login.template.html ---> authorization_code  ----> SPA - access_token 

I think I need silent-refresh as well to update the access token without the user knowing. 

So at a high level its oauth code flow + pkce only. 

Any expert advice is hugely appreciated.

**Comment by stevehobbsdev** [comment]
@godhar Unfortunately this SDK was not designed as a generic OIDC/OAuth2 library and as such it is designed to be quite opinionated when it comes to the flows we implement, including which scopes we use out of the box. As such something like this is low priority for us to work on.

However, I would happily take a look at a PR which implements what you need, that I can use as a basis for internal discussion. Something along the lines of [what is suggested here](https://github.com/auth0/auth0-spa-js/issues/228#issuecomment-538118515) would be a good start.

**Comment by srihari93** [comment]
@stevehobbsdev 
Hi, we are migrating to spa-js from lock and noticed that our JWT's are too fat to fit in the Authorization header. Noticed that the `profile`  scope is being added to our tokens, by default, making them huge.

Can we have a mechanism to have total control over what scopes are included in the token? 
This mechanism was available for lock-js and there is an obvious need for it in the cases where the devs want just enough info to their tokens and not a bit more.

The solution at https://github.com/auth0/auth0-spa-js/issues/228#issuecomment-538118515 above serves our purpose. Will raise a PR if the maintainers are open to it.

> ```
> const auth0 = await createAuth0Client({
>   client_id: 'cid',
>   domain: 'domain.auth0.com',
>   advancedOptions: {
>     defaultScope: 'openid'
>   }
> })
> ```

**Comment by stevehobbsdev** [comment]
@srihari93 Yes, please raise the PR and we can discuss there 👍

**Comment by srihari93** [comment]
@stevehobbsdev done, https://github.com/auth0/auth0-spa-js/pull/389

**Comment by tommmyy** [comment]
I will add another use case. I am trying to use this lib together with Liferay portal. Unfortunately, if I provide the scope, that he do not know, it will return the error "INVALID_SCOPE". 

And there is no way how to add custom scope (https://portal.liferay.dev/docs/7-2/deploy/-/knowledge_base/d/oauth2-scopes) that is named e.g. "email" of "profile" because the Liferay always add its prefix the name of the scope.

**Comment by stevehobbsdev** [comment]
Thanks @tommmyy for the use case. We're working through #389 now and the intention is to merge it, but it needs changes. Bear with us while we work through these.
