### ISSUE TITLE
Mixing authentication from multiple domains

### ISSUE THREAD

**Issue by patricknee** [auth0/auth0-spa-js#257]
I am running development code on two domains: 

qa.example.com
localhost:4200

Both are pointing to the same Auth0 tenant (for testing / development)

In Chrome with two browsers open I log into separate users in each tab (user1@gmail.com on qa.example.com and user2@gmail.com on localhost:4200).

Within about 120 seconds, the earlier of the two tabs reloads (there is a call to the callback page) and it is logged in with the later user.

I would expect the two domains to be handled separately...

**Comment by stevehobbsdev** [comment]
@patricknee Very ood, you're right in that it should be handled separately. Let me look into it.

**Comment by stevehobbsdev** [comment]
@patricknee As it turns out, this is actually working as expected.

The user session is actually held with Auth0. If you're authorizing with the same Auth0 app from multiple instances of your SPA in the same browser, then those apps will get the same user session, even across domains.

One way to mitigate this behaviour (aside from using two different browsers) is to use different tenants, or at least different Auth0 apps, for your development and QA environments. That will give you different app instances and you will be able to work with different users in your scenario.

Closing this for now as it's not really an issue with the SDK itself, but if you'd like to discuss this further, please feel free to raise a question on [Auth0 Community](https://community.auth0.com)
