### ISSUE TITLE
redirect_uri is URI-encoded

### ISSUE THREAD

**Issue by atombender** [auth0/auth0-spa-js#282]
### Description

My code does something like this:

```javascript
await createAuth0Client({
  ...,
  redirect_uri: `${window.location.protocol}//${
    window.location.host
  }/logged-in?return=${window.encodeURIComponent(
    `${window.location.pathname}${window.location.search}`
    )}&myparam=x`
```

The `return` parameter is so that the `/logged-in` handler can know where to send the user back to, and `myparam=x` is necessary as part of our application.

But during the Auth0 flow, the browser is redirected back to the following URL:

```
https://example.com/logged-in?return=%2Fsome-page&amp%3Bmyparam=x&code=[...]&state=[...]#
```

Notice how in the `&myparam=x` part, the ampersand has been URI-encoded. This means I cannot pass more than one additional parameter to the redirect URI because the browser will interpret this as part of the `return` parameter.

This means something has taken the `redirect_uri` and URI-encoded it before sending it, but whatever redirects back doesn't decode it. Since characters like `:`, `.` and `/` are valid URL-encoded characters, I bet nobody has noticed that the decoding is missing, since a URL such as `https://example.com/logged-in` would pass through unmolested.

The user needs to be sent back to `redirect_uri` exactly as provided to the client.

### Environment

- `@auth0/auth0-spa-js@^1.4.1`

**Comment by stevehobbsdev** [comment]
Hey @atombender 

You're right in that we do encode the outgoing parameters. However, the redirect will be actioned by the authorization server, which is where the decoding should happen before the redirect, and so this SDK has no opportunity to get involved with that.

Thus, could you redirect your question to out [Auth0 community site](https://community.auth0.com) where a member of the team will be able to help?

An alternative could be to pass through the information you need through the `appState` property on `loginWithRedirect` instead of relying on the redirect URL. Would this mean that you wouldn't then hit this issue, or is there another reason why you can't use `appState`?

**Comment by stevehobbsdev** [comment]
Closing this for now, if you're still having issues or the `appState` method doesn't fit your scenario, let's discuss it further.
