### ISSUE TITLE
Ability to be used in a WebWorker

### ISSUE THREAD

**Issue by RuneKR** [auth0/auth0-spa-js#302]
### Describe the problem you'd like to have solved
Would like to increase the performance of my app by allowing this to be used in a WebWorker.

### Describe the ideal solution
Get rid of the iframe and use XHR or fetch instead

## Alternatives and current work-arounds
Not use in WebWorker

### Additional context
Happy to contribute if this fit on the roadmap

**Comment by stevehobbsdev** [comment]
@RuneKR Thanks for raising this. We don't have any plans to remove the iframe method in the near future, but we are planning some additions which may allow the use of a normal fetch in addition to the iframe - please stay tuned!

**Comment by tbremer** [comment]
Is there an update on allowing fetch or xhr?

**Comment by stevehobbsdev** [comment]
@tbremer The only thing we have done in this area is to implement [rotating Refresh Tokens](https://auth0.com/docs/libraries/auth0-spa-js#use-rotating-refresh-tokens), which will fetch new access tokens using an XHR call to the token endpoint instead of using an iframe. This is to support browsers where third-party cookies are being blocked by default.

**Comment by tbremer** [comment]
Thanks for the update!
