### ISSUE TITLE
logoutSilently

### ISSUE THREAD

**Issue by franciscolourenco** [auth0/auth0-spa-js#308]
### Describe the problem you'd like to have solved

I would like to perform logout while preserving application state

### Describe the ideal solution

There are no redirects. Logout is performed like getTokenSilently

## Alternatives and current work-arounds

Using an iframe. I this is works when third party cookies are blocked. If not, would it work when a custom domain is setup?

**Comment by stevehobbsdev** [comment]
To answer your question, I don't believe this would work when third-party cookies are blocked, as Auth0 would need to know which session to log out. Yes, it probably would work with custom domains.

Sounds like a good addition and we'd welcome a PR to evaluate it further.

**Comment by dincozdemir** [comment]
Is there any progress on this issue? I'm using a popup login and when im logging out I can't get around the redirect. If i set `localOnly: true` it logs me out, but it will log user in again on page refresh.

**Comment by stevehobbsdev** [comment]
@dincozdemir No progress so far, but will accept a PR.

The local logout issue is interesting though - can you see if the `auth0.is.authenticated` cookie remains after you call `logout({ localOnly: true })`? When you refresh, if that cookie is no longer there, it should not log you in unless you're manually calling `getTokenSilently`.

**Comment by adamjmcgrath** [comment]
Hi @franciscolourenco - we've discussed this internally and decided that we can't offer this feature I'm afraid.

The main issue with `logoutSilently` is that there's no way for the client to know if the logout was successful. `getTokenSilently` works because the Auth server will post credentials back to the client upon successful login (the web_message flow) but there is no openid connect equivalent for logout.

There's nothing stopping you implementing this yourself in your own app, building the logout url is fairly trivial (https://github.com/auth0/auth0-spa-js/blob/master/src/Auth0Client.ts#L715-L726) you'd then need to set your [returnTo](https://auth0.github.io/auth0-spa-js/interfaces/logouturloptions.html#returnto) url to a page on your site that implemented something similar to the web message flow (used postMessage to tell the parent document that the logout was successful and to close the iframe) - but this is out of scope for this SDK.
