### ISSUE TITLE
Use with `prompt=login` or `max_age=0`?

### ISSUE THREAD

**Issue by PeterGFernandez** [auth0/auth0-spa-js#313]
When issuing a redirect to `/authorize` - i.e. via a call to loginWithRedirect() - specifying `prompt=login` or `max_age=0` will force re-authentication by presenting the login dialog even if there is a valid session in the browser. In turn, Auth0 will by default returns tokens with an `auth_time` claim, which can be used to verify that re-authentication occurred (i.e. the `prompt=login` was not explicitly removed). 

However, in `createAuth0Client`, a call to `getTokenSilently` is performed if an authenticated sessions is detected. This will automatically issue a silent authentication - i.e. with `prompt=none` - so any `auth_time` claim will automatically be removed from the issued tokens.

Would it be useful to have a version/variant of  `createAuth0Client` that does not call `getTokenSilently`?

**Comment by stevehobbsdev** [comment]
It needs more thought as to what happens when that check is disabled.

* It means that the session won't be automatically hydrated on the client
* Methods like `getUser` and `isAuthenticated` won't work properly until `getTokenSilently` is called. It doesn't seem like an intuitive way to log the user in silently, so we'd likely put another method in.
* `handleRedirectCallback` would probably still work though

So, is the problem that `getTokenSilently` is executing before `handleRedirectCallback` and removing that claim that you're trying to read?

Probably the best thing to do here is make the changes in a fork and evaluate whether it gets you want you want. Happy to evaluate this further if it's something that you think would work. I'd suggest adding an option to `Auth0ClientOptions` where you can suppress the silent authentication call, which defaults to `false`.

**Comment by stevehobbsdev** [comment]
Adding an option to skip the `getTokenSilently` call is now in our backlog and scheduled to be implemented.

**Comment by stevehobbsdev** [comment]
@PeterGFernandez Today we merged a new addition #377 which allows you to directly access the `Auth0Client` constructor instead of making you use the factory function. This way you can effectively bypass the `getTokenSilently` call on startup. This means at some point you will have to manually call `getTokenSilently` to refresh your session.
