### ISSUE TITLE
IsAuthenticated + Custom scope

### ISSUE THREAD

**Issue by alexander-alvarez** [auth0/auth0-spa-js#321]
### Description

If one is using custom scopes, `isAuthenticated()` no longer works as intended because of cache key mismatch -- it fallsback to check the default scope since no arguments are provided to `getUser`
https://github.com/auth0/auth0-spa-js/blob/2ace866d33cefc8140dceae7437e2a9e61469564/src/Auth0Client.ts#L451

I would expect to be able to pass the required scopes to `isAuthenticated` as I am `getUser`
https://github.com/auth0/auth0-spa-js/blob/2ace866d33cefc8140dceae7437e2a9e61469564/src/Auth0Client.ts#L215

### Reproduction

Provide a custom scope to

```
createAuth0Client(...)
getTokenSilently(...)
loginWithRedirect(...)
// etc
and call `isAuthenticated`
```
### Environment

> Please provide the following:

- **Version of this library used:** 1.6.0
- **Version of the platform or framework used, if applicable:** n/a
- **Other relevant versions (language, server software, OS, browser):** Chrome
- **Other modules/plugins/libraries that might be involved:**

**Comment by kh12e** [comment]
Hi ! is there a workaround about this bug ?

**Comment by ivarprudnikov** [comment]
This issue is missing a concrete example and mixing `createAuth0Client`, `getTokenSilently`, `loginWithRedirect` although those are somewhat different as latter 2 cannot be invoked without running former. More clarification is necessary, could @alexander-alvarez provide more details regarding following points:

Question no 1 - Is this not working as expected?:
```js
const client = await createAuth0Client({
  scope: 'openid profile email foo bar baz', ...
});
// ... skipping redirect handler
client.isAuthenticated();
```
should work as expected because `getUser()` will fall back to `scope` used in `createAuth0Client`.

Question no 2 - Is this not working as expected?:
```js
const client = await createAuth0Client({
  scope: 'openid profile email', ...
});
// ... skipping redirect handler
const accessToken = await client.getTokenSilently({ scope: 'foo bar baz', ... });
client.isAuthenticated();
```
should work as expected because `getUser()` will fall back to `scope` used in `createAuth0Client`, did you expect it to use the scope setting from `getTokenSilently` instead?

Question no 3 - Is this not working as expected?:
```js
const client = await createAuth0Client({ defaults });
// handle authentication redirect
if (window.location.search.includes('code=')) {
  const { appState } = await client.handleRedirectCallback();
}
client.isAuthenticated();

// later in code
client.loginWithRedirect({ scope: 'foo bar baz', ... });
```
Looks like there is a problem here as `handleRedirectCallback` uses `scope` defined in `loginWithRedirect` which might be lost when calling `isAuthenticated` **after redirect**.

**Comment by stevehobbsdev** [comment]
@alexander-alvarez Apologies for the radio silence here. We're not able to reproduce this. If this issue continues to exist using the latest version of the SDK (1.10), please could you report back?

Thanks

**Comment by stevehobbsdev** [comment]
Closing this for now due to inactivity. If there is still an issue to be resolved here, please feel free to raise another issue or continue the conversation.
