### ISSUE TITLE
Checking query.includes(“code=”) && query.includes(“state=”) should be part of Auth0

### ISSUE THREAD

**Issue by jclx** [auth0/auth0-spa-js#340]
This example code seems like Auth0 should provide a util function since we have to look for specific query parameters whose names are set by Auth0 response. Or at least some constants. Could they ever change, it would break all our code using these names.
Version is head.
Something like
boolean auth0.queryIncludesRedirectCallback(window.location.search)
which includes code to validate query includes params for handling redirect callback.

From docs:
// check for the code and state parameters
const query = window.location.search;
if (query.includes(“code=”) && query.includes(“state=”)) {

    // Process the login state
    await auth0.handleRedirectCallback();
...

**Comment by stevehobbsdev** [comment]
👋 Thanks for raising!

This technique is really specific to the application that's using this SDK. The quickstart samples do (and as it happens this may change) this but there are definitely other ways that this could be achieved. For example, one could set a cookie or something into local storage which has the same effect and not look at the query params at all. Or perhaps a flag could be round-tripped through the server and picked up from your app.

Such a function as you describe could be a great utility function for your own app but I'm not sure it fits within the SDK. Happy to discuss other ideas further.

**Comment by jclx** [comment]
As a client, we are not controlling or configuring Auth0 services to put those query parameters on the callback url and naming them. It seems to be a default that Auth0 puts them in the response url. Hence why it seems like it should be part of the API as util method. I don't see the cookie settings.

**Comment by stevehobbsdev** [comment]
I think we're missing a level of indirection here. Yes, Auth0 puts those querystring parameters on the URL and you can't control that for the most part - but I'm not asking you to.

What you're asking about is an application-level detail and not really much to do with the SDK. The SDK just provides the `handleRedirectCallback` method to call; it's up to you and your application as to when you call it.

Your application should detect when a redirect from Auth0 back to your application has occurred. When you detect that, you call the method. **One way** to detect this is by checking the URL for those two parameters, as it's a pretty good (but not foolproof) indication. **Another way** is to get Auth0 to call back to a special 'callback' URL (say `http://your-domain.com/callback`), which means you can guarantee that the callback has happened, making the check on the URL a bit redundant (so you can omit it).

Because this is a detail really specific to your application, such a method as you are proposing doesn't really belong as part of this SDK but as part of your application code.

Does that make it more clear?

**Comment by tnguyen14** [comment]
@stevehobbsdev 

> checking the URL for those two parameters, as it's a pretty good (but not foolproof) indication

Can this method of detection be exposed as an API for this library? That way it can be used by the application/ framework to detect an Auth0 callback page?

**Comment by stevehobbsdev** [comment]
@tnguyen14 Seems like a reasonable request, although I think it would have to be named very carefully. Feel free to raise a PR 👍🏻
