### ISSUE TITLE
failed silent auth login required 

### ISSUE THREAD

**Issue by ttiras** [auth0/auth0-spa-js#345]
Hello,
I am facing an issue and error log is not telling much.
"error": {
"message": "Login required",
"oauthError": "login_required",
"type": "oauth-authorization"
}

and this is in har analyzer:
Cache control
Server's cache control (no-cache, no-store)

Cache data missing
The cache information is missing from the entry

getTokenSilently() is producing this error.
if i switch to getTokenWİthPopup Success Login is logged but the popup keeps opening and closing with producing tokens.

What do you think is the cause?

**Comment by stevehobbsdev** [comment]
Hi @ttiras. You get this error when trying to call `getTokenSilently` in a browser that does not support or otherwise blocks third-party cookie transmission, such as Safari with its ITP technology or Brave with the shields up. Because the cookie cannot be sent to Auth0, we cannot determine whether you are logged in and cannot silently refresh your access token.

Allow me to direct you to [this post on our Community site](https://community.auth0.com/t/failed-silent-auth-login-required/33165/25?u=steve.hobbs) which hopefully has more context for you.

Note that this issue is not limited to Auth0 and we are working on some mitigations for this (please see [this beta release](https://github.com/auth0/auth0-spa-js/releases/tag/v1.7.0-beta.1)).

**Comment by ttiras** [comment]
Hİ Steve, 
Thank you or your help. I understand it is related with the browsers. Can you suggest a workaround for this? I can't find out how to move on. How can i use auth0 under this circumstances. 
Regards

**Comment by VitalieStirbu** [comment]
I have the same issue. I understand that it is related to the browser. But I can't tell the users not to use Iphones (Safari) for the app. Is there a workaround?
@ttiras  how did you solve the issue?

**Comment by stevehobbsdev** [comment]
@VitalieStirbu Can you try installing our beta package `1.7.0-beta.5`? This version allows you to select local storage as a storage option which would get you around this in the short term ([check here for usage](https://github.com/auth0/auth0-spa-js/tree/release/rtr#data-caching)).

Longer term, you will shortly be able to use refresh tokens, which will completely mitigate the effects of third-party cookies in those browsers. It's not quite available for public use yet but that is the long-term solution.

**Comment by VitalieStirbu** [comment]
@stevehobbsdev  sorry for getting back to you so late, but your solution solved the problem. thank you. It's quite interesting that for the non-beta version it was working on Iphone 10,11 but not on 8...

**Comment by thirumalairajr** [comment]
@stevehobbsdev has the long term solution released for this issue. If yes, from which version is it available?

**Comment by tibotiber** [comment]
It's been a few years but love the clear answers on this @stevehobbsdev!

Useful links as of 2024:
https://auth0.com/blog/securing-single-page-applications-with-refresh-token-rotation/
https://auth0.com/docs/secure/tokens/refresh-tokens/refresh-token-rotation
