### ISSUE TITLE
Error on authn when used with Angular router redirect

### ISSUE THREAD

**Issue by humphrej** [auth0/auth0-spa-js#357]
### Description
Received the below error in the browser console when authenticating an Angular application.  The error was caused because my configuration of the Angular router contained a redirect.  I am unsure if this should be supported or not - my workaround is to configure the Angular router without a redirect.
```
ERROR Error: There are no query params available for parsing.
    at e.<anonymous> (vendor.js:98062)
    at vendor.js:98062
    at Object.next (vendor.js:98062)
    at vendor.js:98062
    at new ZoneAwarePromise (polyfills.js:4207)
    at r (vendor.js:98062)
    at e.handleRedirectCallback (vendor.js:98062)
    at MergeMapSubscriber.project (main.js:659)
    at MergeMapSubscriber._tryNext (vendor.js:129058)
    at MergeMapSubscriber._next (vendor.js:129048)
```
### Reproduction
It is reproducible with the 01-Login application in auth0-angular-samples:
1. Clone [my fork](https://github.com/humphrej/auth0-angular-samples).  My fork contains only a change to the [router configuration](https://github.com/humphrej/auth0-angular-samples/commit/4c6bcc89e341a707d5b4693a9bf6ac4547e429ce)
1. Follow instructions in https://auth0.com/docs/quickstart/spa/angular2
1. Click Log In, redirect to Auth0 ok, Google social auth login ok, redirect back to my application 
1. Error in console

### Environment

Tested with auth0-spa-js 1.6.4

**Comment by stevehobbsdev** [comment]
@humphrej This is unfortunately not supported. Right now the SDK relies on being able to parse the `state` and `code` URL parameters on the callback and there are no current plans to change this. Your changes would need to take into account the query params as it redirects.

As this is an issue with the sample itself rather than the SDK, I will close this for now. However, please feel free to file a PR on [the Angular sample](https://github.com/auth0-samples/auth0-angular-samples) if you feel there are changes to be made.
