### ISSUE TITLE
Unhandled Rejection (Error): Invalid state

### ISSUE THREAD

**Issue by gustavo807** [auth0/auth0-spa-js#359]
I set up an app with Saml connection.
![image](https://user-images.githubusercontent.com/15847964/75066225-0ac6cf00-54b0-11ea-95a2-a8c43034bd70.png)

But in my application only receive this
http://localhost:3000/?code=JZGahlVaPU-CwI5a

the state parameter is missing, so how I can include in the Query String field?
Do I need to add extra configuration?

**Comment by gustavo807** [comment]
I got this error
![image](https://user-images.githubusercontent.com/15847964/75066428-701ac000-54b0-11ea-9b28-a668f52cd976.png)

`Uncaught (in promise) Error: Invalid state
    at e.<anonymous> (auth0-spa-js.production.js:2047)
    at auth0-spa-js.production.js:141
    at Object.next (auth0-spa-js.production.js:153)
    at auth0-spa-js.production.js:62
    at new Promise (<anonymous>)
    at r (auth0-spa-js.production.js:39)
    at e.handleRedirectCallback (auth0-spa-js.production.js:2028)
    at initAuth0 (index.js:27)`

**Comment by ylbillyli** [comment]
I get the same error, but some intensive google found this stack overflow answer which help me track down my issue. In my case, it was number 2 the callback is being called twice. Drill down deeper in my case was due to Auth0 is used in a MS Teams Tab which is like an iframe environment and when the sameSite cookie settings is enabled in chrome will fail this... I will post detail in a new issue soon [placeholder for new issue link]

**Comment by stevehobbsdev** [comment]
@gustavo807 It makes sense that you get that error when there is no state param, as the library can't function without that.

However, I'm unclear as to why you're not getting that param. Let me ask internally and report back.

**Comment by gustavo807** [comment]
The issue was in our IdP, we changed the sign-in URL and now works.

**Comment by stevehobbsdev** [comment]
@gustavo807 Thanks for letting us know!
