### ISSUE TITLE
Handle rate limit hit response

### ISSUE THREAD

**Issue by nkete** [auth0/auth0-spa-js#396]
### Description

`getJSON` called by `oauthToken` assumes JSON response. This causes an issue when you hit the rate limit, because in that case the response is
```
HTTP/1.1 429 Too Many Requests
Content-Type: text/html
```
which throws a JSON Parse exception [when parsing the response](https://github.com/auth0/auth0-spa-js/blob/master/src/utils.ts#L198).

### Reproduction

Hit the rate limit :)

The easiest way I found to reliably hit the limit is to add a new method that calls one of the endpoints with more strict limit like `/userinfo` using the `getJSON` method. Something like this.
```js
getJSON(`https://your-tenant-here.auth0.com/userinfo`, {
    method: 'GET',
    headers: {
        'Content-type': 'application/json',
        Authorization: 'Bearer add-token-here',
    }
});
```

### Environment

- **Version of this library used: 1.6.5**

[Link to the PR](https://github.com/auth0/auth0-spa-js/pull/398)

**Comment by stevehobbsdev** [comment]
As mentioned on the associated PR, this is something we've raised some work for within the authz server as it should really be returning JSON to you. Once that fix is rolled out, this should start working for you. Unfortunately I do not have a timeline to share, but I will try to feedback here once I hear that the fix is out.

**Comment by nkete** [comment]
Thanks for the update 👍

**Comment by adamjmcgrath** [comment]
@nkete - am told this is shipped, let me know if you notice any issues
