### ISSUE TITLE
[Question] How to handle browsers starting to reject third-party cookies?

### ISSUE THREAD

**Issue by iainvdw** [auth0/auth0-spa-js#425]
Recently we've implemented the `auth0-spa-js` library as a way to handle auth for our React application. This change was done in light of a security audit to remove the potential of XSS attacks hijacking tokens stored in localStorage.

The change to this method of authentication brought to our attention a different problem: browsers actively rejecting third party cookies, or users enabling third party cookie blocking (either voluntarily or forced because of company guidelines).

How we've currently implemented this library, is by checking for a valid session with Auth0 by doing the `auth0Client.isAuthenticated()` call, after which we fetch a token. This is done for every refresh, new tab, etc. so the SPA doesn't have to store any token in localStorage as the auth information is stored in a third-party cookie at Auth0's end. Here's where the potential problems arise.

When browsers or users start blocking third-party cookies, this library fails to properly identify users actually being logged in. So for every new tab they open or link they click in an email, they have to go through part of the login process again. Pressing the login button would be enough in this case, as Auth0 *does* remember they've logged in before, but it's becoming a pretty big annoyance for some of our users that they have to press "Log in" all the time for new tabs.

I've seen the option to opt in to storing tokens in localStorage, but that would be unfavorable as that was the entire reason why we decided to make this change.

So a couple of questions concerning this matter:
- Would using the custom subdomains feature help in this case? Or would browsers still recognize a subdomain as a third-party domain?
- Would the "Cross-Origin Verification Fallback" setting be of any use?
- Can Auth0 maybe help out in any other way?

**Comment by stevehobbsdev** [comment]
@iainvdw Thanks for raising this. Yes this is a bigger problem than this SDK, browser with more advanced privacy technology such as Safari's ITP blocks our session cookie that prevents this SDK from rehydrating your session when you lose tokens (because of a page refresh, etc).

Using refresh tokens is our answer to that, but again can be easily lost from memory when not using the local storage option.

The other option, as you point out, would be to use custom domains. Because then your app and the authorize call will be on the same origin, they should not be affected by browser technology that block third-party cookies.

**Comment by stevehobbsdev** [comment]
Closing this for now but feel free to continue the discussion if you have more questions.

**Comment by iainvdw** [comment]
Thanks @stevehobbsdev for the answer. We'll start looking into custom domains then to see if that helps us. If I have any further questions, I'll let you know!
