### ISSUE TITLE
login_required requesting accessTokens for different audience

### ISSUE THREAD

**Issue by egadstar** [auth0/auth0-spa-js#469]
### Description

With Safari, I'm seeing "login_required" errors when requesting accessTokens for a different audience when using rotating refresh tokens. 

### Reproduction

I was able to reproduce this by using the Application Quick Start by adjusting a few files and creating two APIs in the Auth0 dashboard:

### auth_config.json
```
{
  "domain": "domain.auth0.com",
  "clientId": "...",
  "audience": "audience1.tenant.com",
  "useRefreshTokens": true,
  "cacheLocation": "localstorage"
}
```

### index.js
```
ReactDOM.render(
  <Auth0Provider
    domain={config.domain}
    client_id={config.clientId}
    redirect_uri={window.location.origin}
    audience={config.audience}
    useRefreshTokens={config.useRefreshTokens}
    cacheLocation={config.cacheLocation}
    onRedirectCallback={onRedirectCallback}
  >
    <App />
  </Auth0Provider>,
  document.getElementById("root")
);
```

### App.js
```
if (loading) {
    return <Loading />;
  } else {
    getTokenSilently().then((accessToken) => console.log("audience 1: ", accessToken)).catch((err) => console.error(err))
    getTokenSilently({ audience: "audience2.tenant.com" }).then((accessToken) => console.log("audience 2: ", accessToken)).catch((err) => console.error(err))
  }
```

### Environment

- 1.8.1
- React Quick Start
- Safari

**Comment by stevehobbsdev** [comment]
@egadstar This is happening because when you specify a new audience, there is a cache miss internally which means that the refresh token you already have cannot be found. In this case, the SDK is falling back to the traditional method of retrieving a new access/refresh token using an iframe and your current Auth0 session. The problem is, this doesn't work in Safari where third-party cookies are being blocked.

This should work in other browsers where third-party cookies are not currently blocked by default (Chrome, Firefox) but in Safari (and other browsers that _do_ block these cookies) the only option you have when getting an access token for a different audience is to put the user through the full interactive flow.

**Comment by andreasgrimm** [comment]
@stevehobbsdev when will this start to work though?

we’re having a setup where the frontend is calling several different “audiences”.

of course we don’t want to re-architect to proxy all of those requests through one “bottleneck audience”.
neither do we want to have a degraded UX like several consecutive logins (one per needed audience) at app start (which would be confusing to users and also not seen amywhere else and would lead to lots of service desk tickets).
nor would we want to deprecate Safari on macOS and iOS just to have the same problems with other browsers in the near future.

**Comment by stevehobbsdev** [comment]
@andreasgrimm Thanks for raising. Auth0 unfortunately doesn't currently support multiple audiences to be specified; I understand it's a tricky problem to solve, with one of the concerns being around scopes - how do you specify what the appropriate scopes are for each audience in a nice way?

One of the patterns we see here is to get an access token for a new audience at the time you need them (rather than on app start) and you can do this using a popup, using `getTokenWithPopup`, specifying the audience and scopes you need.

Does that help?

**Comment by tomboolean** [comment]
We also have multiple audiences / APIs powering multiple parts of the same pages throughout our application. We would really like to tackle this problem. Is there anything else we can do for our use case? If not, is there anything we can help contribute?

**Comment by stevehobbsdev** [comment]
@tomboolean As this a wider issue than just this SDK, I would raise this in our [product feedback portal](https://auth0.com/feedback).

**Comment by tomboolean** [comment]
will do @stevehobbsdev!

Thanks for the help @adamjmcgrath!
