### ISSUE TITLE
Allow `screen_hint: "password-reset"` to open the reset password screen

### ISSUE THREAD

**Issue by fredrik-sogaard** [auth0/auth0-spa-js#473]
Is it possible to allow for `screen_hint: "password-reset"` (or similar) to open the Auth0 screen in the reset password state? Just like it does with `screen_hint: "signup"`.

**Comment by stevehobbsdev** [comment]
Hi @fredrik-sogaard,

Unfortunately this is not currently possible. The only options are to open with the login page or the sign-up page. This is a limitation with the Universal Login Page rather than this SDK, it simply doesn't allow for opening other screens as the default for the moment.

I'll close this for now as it doesn't necessarily relate to this SDK, but feel free to continue the discussion.

**Comment by blimmer** [comment]
Is there any way to do this now, a few years later? Or is it still a limitation of Universal Login?

**Comment by chrisgoodkind** [comment]
As @blimmer asked above, is there any way to prompt forgot password page now? Would be very useful for many people. Thanks

**Comment by frederikprijck** [comment]
@chrisgoodkind i believe nothing has changed regarding supporting that in auth0 server, so there is nothing we can do from the SDK side of afraid.
