### ISSUE TITLE
handleRedirectCallback throws invalid state

### ISSUE THREAD

**Issue by dm2rsq** [auth0/auth0-spa-js#504]
After a successful login initiated from the server side (Node app which delivers the React app), I redirect to my React app where Auth0 has been done following this tutorial: https://auth0.com/docs/quickstart/spa/react/01-login (same domain), but the `handleRedirectCallback` method called from the `initAuth0` method inside the `react-auth0-spa.js` file (see link for details) throws an invalid state error. I'm guessing the issue is the state being set after a Node login and then transferred to React.

After it fails, I've tried adding logic to redirect the page directly to my React login page, but if I do that, I'm just stuck in a loop because the state is always invalid. I've also tried, instead of redirecting the page, calling `loginWithRedirect` when I catch the invalid state error. Again, end up in a loop.

What I'd expect to happen is the following scenario: I login through the request initiated by the Node app, have the state error in React, do `loginWithRedirect` and then get correct state from Auth0, instead of ending up in a loop.

Is something like that supported/doable?

- Version of `auth0-spa-js` used: 1.6.4
- Chrome
- React and Node

**Comment by adamjmcgrath** [comment]
Hi @dm2rsq - thanks fro your report

> After a successful login initiated from the server side (Node app which delivers the React app)

It sounds like your authentication is handled by a server side application, so you shouldn't need auth0-spa-js.

If SPA js hasn't initiated the login (ie you haven't called `loginWithRedirect` on the spa js sdk to login) then when you login through some other method and visit the redirect url with a `state` param, SPA JS will not know what to do with that param - so will throw an `Invalid State` error.

**Comment by dm2rsq** [comment]
Yes, I thought that was the case. The reason for this flow is to avoid serving the React app if a user hasn't been logged in. Once I login through the server side - could I use the access token obtained from the server side inside the React app and have it considered as a valid access token? I don't think there should be an issue for that kind of flow.
If that's possible - is there a method in SPA that I can use just to check if the token is valid, regardless of the login?

**Comment by stevehobbsdev** [comment]
@dm2rsq The checking of whether the access token is valid is the job of the API that you use the token to call. It is not recommended to inspect the contents of the access token (to check its valididity or otherwise) inside the thing that has requested the token. As such, we don't have such a method inside this SDK to support that scenario. We don't do this ourselves, since it's not the SDKs responsibility to validate access tokens.

You can certainly pass the access token to your React frontend somehow for use by the frontend app - that architecture is up to you, however you want to do it. Remember that anyone who has that access token can effectively call the target API, so following good guidelines to make sure the access token is protected is recommended.

Closing this issue as it's not really related to a bug in the SDK, but feel free to continue the conversation if you have more to add.
