### ISSUE TITLE
getTokenSilently waits for timeout even if call rejected

### ISSUE THREAD

**Issue by jongrim** [auth0/auth0-spa-js#507]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem

When calling `getTokenSilently` to a misconfigured tenant, the underlying call to `/authorize` may result in a 40X error. The request is ended, but `getTokenSilently` waits for the timeout before rejecting.

### What was the expected behavior?

I expected that if the underlying call to `/authorize` fails, the promise would reject immediately.

### Reproduction
I have reproduced the issue [here](https://github.com/jongrim/auth0-reject-bug). This is a copy of the [auth0-react-samples](https://github.com/auth0-samples/auth0-react-samples) with one modification. I added a call to `getTokenSilently` [on this line](https://github.com/jongrim/auth0-reject-bug/blob/master/01-Login/src/react-auth0-spa.js#L33). The other crucial setup piece is that the auth 0 tenant to which this calls out does not have this origin as an allowed callback or origin. That is what generates the error in the `/authorize` call.

You can see from the screenshot that the network call has failed, but the app still shows loading because it is waiting for the timeout.

<img width="1429" alt="Screen Shot 2020-06-15 at 9 36 43 AM" src="https://user-images.githubusercontent.com/5757520/84664435-8b408e00-aeec-11ea-8a77-42575b442525.png">

### Environment

> Please provide the following:

- **Version of `auth0-spa-js` used:**: `^1.0.2`
- **Which browsers have you tested in?**: chrome
- **Which framework are you using, if applicable (Angular, React, etc):** React
- **Other modules/plugins/libraries that might be involved:** none

**Comment by stevehobbsdev** [comment]
Thanks for raising this @jongrim - this is a known issue](https://github.com/auth0/auth0-spa-js/blob/master/FAQ.md#why-does-the-auth0client-object-take-a-long-time-to-initialize). The problem here is that when you have a misconfigured tenant, Auth0 server (by design) does not report the error back to us via a `postMessage` call. The transaction to get a new access token happens by default in an iframe via the Message API. This is why we need the timeout; because we never receive the response from the server that would allow us to handle the error, the only thing we can do is wait for the timeout.

Unfortunately we cannot change the behaviour on the server, but you are able to [configure the timeout](https://auth0.github.io/auth0-spa-js/interfaces/auth0clientoptions.html#authorizetimeoutinseconds) to be much shorter if you wish:

```
await createAuth0Client({
  // ... other params
  authorizeTimeoutInSeconds: 10
});
```
