### ISSUE TITLE
Invalid state with cross origin redirect - ability to use custom state?

### ISSUE THREAD

**Issue by Enngage** [auth0/auth0-spa-js#548]
Hey,

I'm getting ```invalid state``` error when I use different ```redirect_uri``` domain. 

Basically on `mydomain.com` I trigger `loginWithRedirect` which redirects to `app.mydomain.com/auth/external`.

Is this scenario supported? I was thinking that if I could manage state manually, I could verify that its ok myself.

Before the cookies were blocked I used silent log-in which worked perfectly fine across these domains, but it has stopped working sand I'm trying to find a workaround. 

Currently I do javascript redirect from `mydomain.com` to `app.mydomain.com` and trigger `loginWithRedirect` there which is working fine, but I would really like to avoid this redirect. 

Thank you for any suggestions :-)

**Comment by stevehobbsdev** [comment]
Hi @Enngage, right now that scenario is not supported as the cookies we set that are involved in the auth transaction are host-only cookies, and not available to subdomains. This is why you're getting the `invalid state` error; the cookie we use to match the state can't be found. The current recommendation is to do continue to do the redirect as you are now, as ugly as it may be.

We are planning some changes in this area to solve some other problems that we're having, so maybe this is an area that we can support in the future.

**Comment by JohnnyTMD** [comment]
Hi, I have the same issue, I start the login process on domain.com and it goes to the custom login page and then the user get's redirected to dashboard.domain.com . Same error I see: Invalid state. However if I call getTokenSilently() I get the token and I'm able to do the other API requests. When the user refresh the page he is gets logged out. 
Any updates on this? @stevehobbsdev

**Comment by stevehobbsdev** [comment]
@JohnnyTMD I suspect you're running into this because the SDK uses session storage by default to handle auth transactions, and `state` is stored inside this transaction. For this scenario you can try enabling `useCookiesForTransactions` ([docs](https://auth0.github.io/auth0-spa-js/interfaces/auth0clientoptions.html#usecookiesfortransactions)) which, as the name suggests, causes the SDK to use cookies to handle this transaction and is by default scoped to the top level domain.

Let me know if that solves your issue.

**Comment by JohnnyTMD** [comment]
Hi @stevehobbsdev , I've tried that but didn't help (
