### ISSUE TITLE
Setting custom state for loginWithRedirect and handleRedirectCallback

### ISSUE THREAD

**Issue by freeman-g** [auth0/auth0-spa-js#574]
### Describe the problem you'd like to have solved

I am working on a SPA based on Svelte.js that will have some secured routes and some unsecured routes. Within my application I'm using a frontend router but I'm having a problem with parsing the Auth0 state param after the frontend router routes to my Svelte components that need to be secured.

The issue I'm having is that the frontend router is changing the URL from something like `state=M1NQUnBTdFp0Z2kwTFlmTW5laTdvaXhDOG5TRERFNTNPQWlmdWE3OVpJMg%3D%3D` to `state=M1NQUnBTdFp0Z2kwTFlmTW5laTdvaXhDOG5TRERFNTNPQWlmdWE3OVpJMg==`.

This causes an invalid state issue because the URL is already changed by the time the async handleRedirectCallback is called.

Obviously, this is not an Auth0 issue, but if I could set my own state for the loginWithRedirect and handleRedirectCallback functions, then I could work around the issue.

### Describe the ideal solution

Ideally, I could do the following:

1. Set my own state hash string
2. Store it in local storage
3. Pass it to the loginWithRedirect function
4. On the call back, fetch it from local storage
5. Pass it to the handleRedirectCallback function

I believe this is possible in the standard Auth0 JS library.

Thank you

**Comment by stevehobbsdev** [comment]
@freeman-g We already have a mechanism for doing this that does not involve using the state param. You're able to set [`appState`](https://auth0.github.io/auth0-spa-js/interfaces/redirectloginoptions.html#appstate) when you call `loginWithRedirect`, then you [get it back when you call `handleRedirectCallback`](https://auth0.github.io/auth0-spa-js/interfaces/redirectloginresult.html).

```js
// set state
client.loginWithRedirect({
  appState: { someValue: true }
});

// Retrieve the state
const { appState } = handleRedirectCallback();
```

Does that meet your needs?

**Comment by freeman-g** [comment]
@stevehobbsdev, thank you for the response. I think my case is a little different. I want to be able to do this:

```
const myState = '39ulkna9dklnl2k39knliad9sdlknasldk93'
window.localStorage.setItem('state', myState)
client.loginWithRedirect({
  state: myState
});

// then later

const myState = window.localStorage.getItem('state')
handleRedirectCallback({
  state: myState
})

// state is valid
```

**Comment by stevehobbsdev** [comment]
@freeman-g Apologies, after a second read I realise now that my response really doesn't help your use case at all.

I think rather than allowing you to specify your own state string, we look at why the states are coming back differently. It looks like it's just trying to compare a URL-encoded version with a non-URL encoded version. You mention it's not the fault of the SDK but we have seen this before, and I don't think Svelte was involved or at least some steps; unfortunately we could not reproduce it.

Do you have a bare-bones app you could share that demonstrates the problem, so that we may get a look? It feels like something we should handle in the SDK rather than try to work around it.

**Comment by freeman-g** [comment]
@stevehobbsdev I went to create a small Svelte app to demonstrate the issue and did a fresh `npm install @auth0/auth0-spa-js` which put me at 1.12.0 and I am no longer having this issue.

I back tested with 1.11 and did have the issue, so it appears to be fixed in 1.12. Which is great for me...thank you for your assistance.

**Comment by stevehobbsdev** [comment]
No worries, although I'm struggling to think now of a change that would have fixed that specific issue. Let us know if you encounter it again!

**Comment by matootie** [comment]
Hello!

I don't mean to dig up an old issue but I'm pretty sure setting custom state for `loginWithRedirect` and `handleRedirectCallback` is exactly what I need.

I have a React application (using `@auth0/auth0-react`) that will call `loginWithRedirect`. After authorization the user is redirected to a specific API endpoint that will evaluate something and then send the user back to the client. This API endpoint receives `state` and `code` in querystring parameters as part of the authorization process. It does what it needs to do, and then sends the user back to the client passing along the `state` and `code` querystring parameters so `@auth0/auth0-react` can then wrap up authorization accordingly with `handleRedirectCallback`. 

I need to send a small amount of information to the API that it will use post-authorization. Because the user is being redirected to an API endpoint and not the React application, I can't use `TransactionManager` and `appState`. For that reason `state` is the only way I can pass along some data to the API for it to use post-authorization. However it seems that using this library I can't control what its value is.

Functionality similar to this is advertised on this page https://auth0.com/docs/secure/attack-protection/state-parameters but it doesn't look like it's possible with this library.

In full, I'm trying to implement this entire flow:
1. Client calls API sending some data
2. API generates `state` and stores the data from the client in a key-value database with `state` as the key
3. Client starts authorization process using `loginWithRedirect` passing `state` provided from API _(doesn't seem possible using this library)_
4. Auth0 redirects to API after authorization, passing `state` and `code`
5. API uses `state` to retrieve data from database, does something
6. API redirects to client forwarding `state` and `code`
7. Client finishes the authorization process using `handleRedirectCallback`

I've been reading through a lot of documentation and old issues to see if there's a way, or maybe another approach I can take. I came across issue https://github.com/auth0/auth0-spa-js/issues/747#issuecomment-844849143 with the comment:

> In this case, this SDK is protecting against CSRF by using PKCE but still uses State to transport data.

Is this library using `state` to transport data? A quick look at the source code https://github.com/auth0/auth0-spa-js/blob/main/src/Auth0Client.ts#L298 and it seems it's just a randomly generated string. Based on the above comment, it's not used to protect against CSRF. If currently there's no specific use for state can we provide the ability to set a custom state value?
