### ISSUE TITLE
Silent Auth Fails in Chrome 83+ Incognito Mode

### ISSUE THREAD

**Issue by randalvance** [auth0/auth0-spa-js#577]
## Description
Silent Authentication always fails in Chrome only when you are in incognito mode.

I've checked the network requests to `authorize` endpoint and notice these differences:

Normal Chrome
![image](https://user-images.githubusercontent.com/3318476/93096224-b64aa180-f6d6-11ea-8d56-aba23d588631.png)

Incognito Mode
![image](https://user-images.githubusercontent.com/3318476/93096204-afbc2a00-f6d6-11ea-845f-fe1683f8681e.png)

There is a warning icon that says this when you hover:
The Set-Cookie was blocked due to user preferences.

Looks like there was a recent change made in Chrome 83
https://angel.co/today/stories/chrome-83-arrives-with-redesigned-security-settings-third-party-cookies-blocked-in-incognito-21796

Tried this as well in Edge Chromimum In-Private mode and it's working correctly.

### Expected Behavior
I am still logged in even if I refresh the page in Chrome Incognito.

### Environment
Chrome 83+
Windows 10

> Please provide the following:

- **Version of `auth0-spa-js` used:**
1.12.0
- **Which browsers have you tested in?**
Chrome 85 Incognito
- **Which framework are you using, if applicable (Angular, React, etc):**
Vue

**Comment by stevehobbsdev** [comment]
Yes - this SDK currently requires third-party cookie support by default for silent authentication to work. Since Chrome has started blocking such cookies in Incognito mode, you will have to switch to using [Rotation Refresh Tokens](https://auth0.com/blog/securing-single-page-applications-with-refresh-token-rotation/) in order for silent authentication to work. This does not require access to the session cookie to work, and should work ok in Incognito mode.

**Comment by eric-jiang** [comment]
Just wondering with the introduce to dual auth0-compact and auth0 cookies, would the issue reported be resolved automatically?

**Comment by stevehobbsdev** [comment]
@eric-jiang Unfortunately not. The two cookies you mention are designed to allow older browsers that do not support the SameSite attribute to continue working, which is a different thing from third-party cookie blocking (in this case, both cookies will be blocked).
