### ISSUE TITLE
Invalid state error with foo.auth0.com being assigned to a Firefox container

### ISSUE THREAD

**Issue by jplatte** [auth0/auth0-spa-js#580]
### Describe the problem

When logging into our app that uses Auth0, after Firefox opening Auth0 in a new tab with a different browser context because I've set it to always open in my work [container](https://support.mozilla.org/en-US/kb/containers) and me logging in, I'm getting the following error:

![Screenshot_2020-09-18](https://user-images.githubusercontent.com/951129/93586966-6fe09580-f9a9-11ea-88f5-16876c8d06aa.png)

### What was the expected behavior?

Login succeeding.

### Reproduction

- Install [Multi-Account Containers](https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/) for Firefox
- Go to `something.auth0.com`
- In the Multi-Account Containers menu, set "Always open this site in" to some container
- Try to login on a page using `something.auth0.com` for authentication from outside that container
- (You should see `something.auth0.com` open in a separate containerized tab)
- Try to log in

### Environment

> Please provide the following:

- **Version of `auth0-spa-js` used:** `package.json` has `^1.6.4`, so since I just ran `yarn install` probably the latest one
- **Which browsers have you tested in?** Firefox
- **Which framework are you using, if applicable (Angular, React, etc):** React

**Comment by stevehobbsdev** [comment]
@jplatte Can you determine exactly which version of the SDK you have installed through the lock file? It makes a difference as we recently changed how transaction state is stored internally, just want to make sure we're on the same page when we investigate.

**Comment by jplatte** [comment]
This?

```yaml
"@auth0/auth0-spa-js@^1.6.4":
  version "1.11.0"
  resolved "https://registry.yarnpkg.com/@auth0/auth0-spa-js/-/auth0-spa-js-1.11.0.tgz#800a59ddeaa11ad8a94a699c58f9971842ea065f"
  integrity sha512-PHYykO4IoEGeTT2SVzvZiJNK5QgznLJweJfVcb0C8X+rZYooBN5Qrdj0AfECzgK9h90kfU4u3s9h83VTSh6t3A==
```

**Comment by stevehobbsdev** [comment]
Can you run another upgrade and verify whether or not it now works? We recently released 1.12.1 which changes the way transactions are stored. Interested in if it's a problem with cookies vs. Session storage.

**Comment by jplatte** [comment]
Same issue with 1.21.1. Line numbers shifted a bit, but otherwise the error still looks exactly the same.

**Comment by stevehobbsdev** [comment]
Thanks. On the readme for containers:

> Under the hood, it separates website storage into tab-specific Containers. Cookies downloaded by one Container are not available to other Containers.

So in this case I would not expect the SDK to work with containers in the way that you are using them. In the flow between your app -> Auth0 -> back to your app, the SDK stores some transactional information so that we are able to verify certain things about the tokens you receive, in "the state". Looks like the SDK cannot read the state because after login, it's now running in a different container and thus has no access to it's transaction information.

In pre-1.12 we stored this information in a cookie. From 1.12 we use session storage for this, and it looks like containers segregate session storage as well.

For this to work, you will have to run the entire flow in the same container, not just the Auth0 part. You will have to start the login process from your app inside the work container too.

Does that help? Closing for now but feel free to continue the conversation.

**Comment by jplatte** [comment]
Okay. I *think* I've seen login succeed with the login page being opened in a different container from the one where the login was initiated (such that the container the login was actually performed in then had a working session), but if that is not going to work that's okay.

However, it still seems to me like your error handling could be improved here. Would it be possible for auth0-spa-js to retry login in this error condition?

**Comment by stevehobbsdev** [comment]
> Would it be possible for auth0-spa-js to retry login in this error condition?

We'd prefer not to make assumptions about how the developer wants to handle that. It's pretty much a catastrophic error that you would not normally see unless something unexpected happened (like performing the login flow in different containers). If the SDK is being used in an unexpected way where the state was _never_ available and we automatically redirect away again, the user would end up in a redirect loop.
