### ISSUE TITLE
Auth0 bundle size

### ISSUE THREAD

**Issue by delwyn** [auth0/auth0-spa-js#608]
### Auth0 bundle size

Hi, I just noticed that when updating from 1.12.1 to 1.13, our bundle size when up a lot. 

1.12.1 auth0-spa-js.production.esm.js is 93K
1.13 auth0-spa-js.production.esm.js is 138K

That is basically a 50% increase. I realise that this is mainly due to the AbortController polyfill #598 but this seems like a really big change. Is there any way of potentially excluding this from the build and requiring people that need it to include it them selves?

Thanks

**Comment by stevehobbsdev** [comment]
Thanks for raising @delwyn - it's something we are aware of and are working to resolve. I don't have a timeline or a fix right at this moment but we'll keep a note to make you aware once we have deployed a fix.

**Comment by wooque** [comment]
@stevehobbsdev Why is this issue closed? Is it fixed? I noticed same issue

**Comment by stevehobbsdev** [comment]
Hi all,

We will be patching this back out and fixing the original issue in a different way to try and bring this bundle size back down, so I have reopened this issue for now. Thanks for the feedback!

cc @wooque

**Comment by frederikprijck** [comment]
The bundle size has been reduced again in 1.13.1, which has just been released.

**Comment by twilly86** [comment]
are you sure? i'm still seeing around 130kb
https://bundlephobia.com/result?p=@auth0/auth0-spa-js@1.13.6

**Comment by frederikprijck** [comment]
Hey @twilly86 ,

Sorry, my comment might have been a bit misleading. We didn't revert the bundle size to what it was in 1.12.1, we reverted the changes for the polyfill that got added in https://github.com/auth0/auth0-spa-js/pull/598, which was causing unexpected increases in size.

The main issue, as being pointed out already, is the fact that we are including a lot of polyfills. We have been adding features without changing any browser support or without excluding the polyfills from our bundle. Along the way we even had to add extra polyfills, e.g. between 1.12.1 and 1.13.6, 20Kb of our bundle increase (pre-compression) is due to core-js increase only.

We are still planning to change how we include polyfills in the future. But for now, I think the 130kb is, sadly, expected.
That said, I hope that, somewhere soon, we are in a position we can make most, if not all, polyfills opt-in, which should reduce the bundle by more than 50%. However, as this change involves a major version, these are things that will happen alongside other breaking changes that are in our backlog. For now, there is no ETA on this yet.

**Comment by mmospanenko** [comment]
1.19.4 - 90.4K :'(

I want only login (get token) and logout functions, I don't want to bring everything to bundle. I hope it is possible to call http directly...

**Comment by amit-kapadia** [comment]
This is a joke!

**Comment by glcheetham** [comment]
@frederikprijck thanks for the in-depth reply. How far back in time do you polyfill to? e.g I don't need ie6-10 for my project so I could fork and drop the polyfills to make an auth0 "lite" @stevehobbsdev ?
