### ISSUE TITLE
Store refresh tokens in localStorage whilst storing access & id tokens in memory

### ISSUE THREAD

**Issue by markdBC** [auth0/auth0-spa-js#615]
### Describe the problem you'd like to have solved

I am trying to implement authentication for browsers which do not have 3rd party cookies enabled (e.g. Safari). I am planning to use refresh tokens to achieve this.

The default cache location for tokens is currently `memory`, in which case the refresh tokens are lost if the page is refreshed. Without 3rd party cookies, the user is forced to type in their credentials again.

This problem goes away if we use `localStorage` instead. However, we will then be persisting access tokens in the browser. This is problematic since access tokens cannot be revoked while they have not expired. An attacker that gets hold of an unexpired access token from local storage (e.g. via a XSS vulnerability) would have unlimited access to our API.

### Describe the ideal solution

Allow 'hybrid' cache storage, where (rotated) refresh tokens are stored in local storage but access & id tokens are stored in memory.

## Alternatives and current work-arounds

I am currently using `localStorage`. Once tokens have been retrieved, I store the id & access tokens in `memory` and remove them from `localStorage`.

**Comment by stevehobbsdev** [comment]
This is an interesting take @markdBC, thanks for raising.

We recognise the risks when using local storage to store such tokens and [have outlined them in our docs](https://auth0.com/docs/tokens/token-storage#browser-local-storage-scenarios). Generally there are a few best practises to follow:

* Use as short an expiry time on your access tokens as is practical
* Reduce the amount of third-party JavaScript running on your app and perform all due dilligence to prevent an XSS attack from succeeding. 

That being said, let me take it to the team and come back to you next week.

**Comment by markdBC** [comment]
@stevehobbsdev Any news on this?

**Comment by stevehobbsdev** [comment]
@markdBC Yes, I had it in mind to come back with a response today, sorry for keeping you waiting.

After discussing with the development and security teams, we've decided that while it's an interesting idea on the surface, it's not something we'll be implementing at this time. Storing the tokens separately in this way would solve a very small use-case as you describe, but at the end of the day a successful attacker could just use the refresh token to get another access token and use that - they would not need to steal the access token you already have, and you end up in the same position. At the same time, it adds a maintenance and potential reliability cost to the SDK for only a very small benefit.

Of course, using a stolen refresh token will kick in the built-in reuse detection mechanism but they would still have an access token they can use, which is why the mitigations I mentioned in my previous comment are still very important - use access tokens with as small a lifetime as you can get away with, and deploy as many tactics as you can to mitigate against XSS attacks in the first place.

Again, thanks for raising it to our attention!

**Comment by markdBC** [comment]
@stevehobbsdev Thanks for the explanation. I think I agree.
