### ISSUE TITLE
Unhandled Rejection (Error): Invalid State

### ISSUE THREAD

**Issue by yirenlu92** [auth0/auth0-spa-js#68]
I am calling auth0 using the methods provided in react-auth0-wrapper.js. Sporadically I am receiving the following error when I try to login:
![IMG-9801](https://user-images.githubusercontent.com/13631199/61176341-3cc49a00-a58d-11e9-866c-e77ec2984193.JPG)
Documentation online says that it's possibly a caching problem, but the documentation is wordpress-plugin-specific. Anyone know what's going on here?
Thanks!

**Comment by luisrudge** [comment]
This happens a lot in test scenarios, when you go to the Universal Login page (after calling `loginWithRedirect` and then click the browser back button to go back to your app to test it again. If you do that a lot, it will cause this issue where you fill up the available cookie space with transactions that never get finished.

Also, might happen if you're calling `loginWithRedirect` more than once when you have a bug in your code, like allowing users to double click a ‘login’ button for example.

In any case, clearing cookies and trying again will most likely fix this issue during development time. In production, it's highly unlikely that users will hit this issue.

**Comment by AntoLepejian** [comment]
Hey,

So I am also running into this same problem every single time I try to login (my app and even the sample one i downloaded from quickstart). what I found was that I press the login button and it takes me to the universal login page, I then continue with face and when it redirects me to my website, the url is
`http://localhost:3000/?code=QzXu82CDUz4mWykJ&state=STFZb3JPZGZiMVdQSk5aV1drSkVwd2VLSzNYWE0zS09DZEJFTlBmNTlFQQ%3D%3D#_=_` and I get the invalid state error with this error in the console
`Uncaught (in promise) Error: Invalid state
    at t.<anonymous> (auth0-spa-js.production.js:1653)
    at auth0-spa-js.production.js:141
    at Object.next (auth0-spa-js.production.js:153)
    at auth0-spa-js.production.js:62
    at new Promise (<anonymous>)
    at r (auth0-spa-js.production.js:39)
    at t.handleRedirectCallback (auth0-spa-js.production.js:1639)
    at initAuth0 (react-auth0-spa.js:26)`

However, immediately after, if I go to localhost:3000 and click login again I get logged in without going through the universal login page.

I tried clearing cookies, caches, local storage etc.. even incognito and other browsers. The issue happens every time both on localhost and in production mode.

**Comment by techieshark** [comment]
I also see this issue, and it occurs for me using the email login (magic link login) when you start the login in one browser and finish it in another.  

For example, this happens when using iOS and the login process starts with a preferred browser like Chrome or Firefox but the login process finishes with the one iOS opens the link from, which will be the default (but not preferred) app, Safari.

**Comment by stevehobbsdev** [comment]
@techieshark This is a concern and I can understand why it's happening in your case. Since the state is cached in a cookie, the cookie won't be available when you start login using one browser but return to handle it in a different browser.

**Comment by dearamerican** [comment]
Hey there,
I also had this problem with a basic react app. I had no problems with a custom signup form, but when I decided I'd prefer to use the Auth0 Lock form, it took me two days to make it work.

Clearing cookies had no effect on the problem. I was never clicking the browser back button. What seemed to trigger this issue was adding the following to the options parameter passed to Auth0Lock: 
```
    auth: {
       redirectUrl: redirect
    }

```
It may be worth noting that the redirect above is a localhost url.

I solved the issue by taking that redirectUrl option out. Instead, I set a 'loggedIn' variable on state, and when true `return (<>{loginWithRedirect()}</>);`

Hope that's helpful for someone.

**Comment by sprazzeus** [comment]
My error is slightly different (this file uses `createAuthClient` from `auth0-spa-js`):
```
Unhandled Rejection (Error): Invalid state
▶ 6 stack frames were collapsed.
_callee$
src/components/Auth/react-auth0-spa.js:25

  22 | const [idToken, setIdToken] = useState("");
  23 | 
  24 | useEffect(() => {
> 25 |   const initAuth0 = async () => {
     | ^  26 |     const auth0FromHook = await createAuth0Client(initOptions);
  27 |     setAuth0(auth0FromHook);
```

@luisrudge would this be related to @yirenlu92's? I encountered this error upon the first login, so it doesn't seem to be due to filling up cookie space as suggested. Then I tried logging in again with cookies cleared, implying that this is not caused by revisiting the auth page (via back button or otherwise), nor cookies.

For context, I'm using Hasura's React/GraphQL/Auth0 boilerplate from https://hasura.io/learn/graphql/react/setup/ and the `loginWithRedirect()` function seems to be only called once, via a button `onClick` event.
