### ISSUE TITLE
WebCrypto: "The requested operation is unsupported" on iOS 13.6

### ISSUE THREAD

**Issue by markatlish** [auth0/auth0-spa-js#685]
### Reproduction
Using auth0-spa-js v1.13.3 we are seeing an exception "The requested operation is unsupported" on Mobile Safari 13.1.2 / iOS 13.6.1 upon `loginWithRedirect`.  It appears this is related to WebCryto used in auth0-spa-js

(We have not tested to reproduce this but are reporting it after seeing it in production error reports, in case it's of interest to others. For context, a similar issue was reported on the AMP project here: https://github.com/ampproject/amphtml/issues/6676)

**Comment by stevehobbsdev** [comment]
Thanks for the report. The Crypto Subtle APIs we used are [supported back to iOS Safari 10.3](https://caniuse.com/mdn-api_crypto_subtle) without a prefix, and I can't reproduce any particular issues here on those versions of Safari.

If you manage to develop a reliable reproduction of this error, please raise another issue and complete the issue template that we provide, so that we are better able to identify and resolve the problem.
