### ISSUE TITLE
Need a way to get the id_token

### ISSUE THREAD

**Issue by flunderpero** [auth0/auth0-spa-js#693]
### Describe the problem you'd like to have solved

In the previous API we were able to get the actual `id_token`, but with the new API we are not. We need this, because we send it to the server where we decode it and extract all the information about the user and claims there. 
We currently have a "workaround" where we directly tap into `Auth0Client.cache`, but this is brittle as I learned today (the CacheKey format changed) :-)

### Describe the ideal solution

`Auth0Client.getIdToken()`

**Comment by flunderpero** [comment]
Just found a "better" workaround: `(await Auth0Client.getIdTokenClaims()).__raw` contains the id-token. But this is still hacking ...

**Comment by frederikprijck** [comment]
Hi @flunderpero,

The Auth0 Docs mention the following about ID Tokens in https://auth0.com/docs/tokens: 

> Do not use ID tokens to gain access to an API. Each token contains information for the intended audience (which is usually the recipient). According to the OpenID Connect specification, the audience of the ID token (indicated by the aud claim) must be the client ID of the application making the authentication request. If this is not the case, you should not trust the token.

Basically, this means that the ID Token is supposed to be used in the application that is requesting the tokens, which is the SPA application in this case, and not the API.

Access Tokens is what is supposed to be sent to the API. It might be the case that the Access Token does not contain the information your API needs in order to make access decisions, but the ID Token does. The idea here is to enrich the Access Token with the information required by the API in such a way that it can make proper decisions about accessing the API (roles, scopes etc). This enrichment can be done using Auth0 rules:  https://auth0.com/docs/rules

The rules documentation mention that one of the things rules can be used for is:

- Modify tokens: Change the returned scopes of the Access Token and/or add claims to it, and to the ID Token.

I think this is what you are looking for. Using a rule you can ensure the Access Token includes the same information that you also have in the ID Token that your API needs for making appropriate access decisions.

That said, I also want to point out that there are other ways you can get user information into your API. One of the ways could be to query Auth0's Management API for a user https://auth0.com/docs/api/management/v2#!/Users/get_users_by_id.
This can be useful if you need extra information in your API about the user that is not required to make access decision (like additional profile information that is being stored).

The purpose of an ID Token is not to sync Auth0's user info to your own API/Database, thats where other things such as the Management API come into play. The purpose of the ID Token is to send profile information to the application that is requesting this information, being the SPA in this case.

You can also get the separate claims using `getIdTokenClaims` and send them to your own API, but I do not think exposing the ID Token in the SDK is needed here (and I would also discourage using `__raw` to get a hold on the ID Token using the internal API.

**Comment by flunderpero** [comment]
@frederikprijck I understand your reasoning. We are not using the idToken to authenticate or authorise, we use it merely as a means of setting profile information in our backend. We already use rules to populate both, the access- and the idToken with additional claims, but we don't want to pollute the access-token with information that is not related to authentication / authorisation such as profile information.
The workaround is fine for now and we'll look into other ways to update the profile information on our servers. Thanks for the quick and detailed response!

**Comment by iongion** [comment]
Sorry for necro-posting

> You can also get the separate claims using getIdTokenClaims and send them to your own API to store them in your own system if needed.

I am on the same problem, I don't want to use to id-token to provide login to my app, I wills use it to create an internal access token that is tied to a validated legacy mechanism of permissions. I am not considering this an invalidation of good practice as I use it only once, to validate the user's identity.

Back to using "good practice" of access token, which in my case, it does not provide any access, it just provides who the user is in the legacy system context that I am trying to migrate to auth0, but it is hard, I can't move permissions into Auth0's own at once. And this incomplete, that's why I need the id token, it is more fitting.

What to do ?

1. Use management API to call Auth0, it is secure, but no, why should I do an additional call to Auth0 ? It is a high frequency system, lots of websocket ephemeral traffic controlling some machinery ? This not only it is not needed, but also will cause slowdowns for both my app and auth0, will get rate limited ...
2. There is the suggestion to have the app send the user profile together with the access token so that the API realizes and creates or matches user accounts ? But then, this profile can be tampered with, it is not such a good idea, it is insecure and also prone to accidents. The ID token is signed, the profile is a plain object, if I send it over the wire, the other side has to validate if the data was not modified on the way and it cannot, how should it be signed ? By the client ?(no). So then again, ID token is better, it is already signed by Auth0. I am sure email and username are what they are.

I don't know what to do anymore - `__raw` is too raw, any more tips ?

**Comment by frederikprijck** [comment]
@iongion If you need the actual ID token, the only way through our SDK is by using the `__raw` claim.
