### ISSUE TITLE
Incorrect redirect with onRedirectCallback

### ISSUE THREAD

**Issue by mmykhaylov** [auth0/auth0-spa-js#696]
### Describe the problem

I am trying to secure a route in my react application, where the routing is handled by react-router-dom. Following the guide, I am passing an onRedirectCallback to the Auth0Provider and secure the route with withAuthenticationRequired. However, doing so breaks the login from both the login button and the redirect from the protected route.

The process goes like this:

1. Click login button or go to a protected route
2. Get redirected to Auth0 login page
3. Fill out the details and click log in
4. I get redirected to `/${appState.returnTo}`, the component flashes for a second, then get redirected to `/${appState.returnTo}?code=CODE&state=STATE`, and the component disappears.
5. React Dev Tools confirms that the route is indeed not rendering, even though it should
6. Reloading the page doesnt fix anything, removing "?code=CODE&state=STATE" from the path and reloading displays the component and the user is shown logged in

### What was the expected behavior?

I should be redirected to the root when logging in manually and to the protected route if the user went there

### Reproduction

> Detail the steps taken to reproduce this error, and whether this issue can be reproduced consistently or if it is intermittent.
> **Note**: If clear, reproducable steps or the smallest sample app demonstrating misbehavior cannot be provided, we may not be able to follow up on this bug report.

```
git clone https://github.com/mmykhaylov/auth0-issue
cd auth0-issue
yarn install
touch .env
```
Provide .env file:
```
DOMAIN=YOURDOMAIN
CLIENTID=YOURCLIENTID
```
After that
```
yarn build
yarn start
```

Then follow the instructions above

### Environment

> Please provide the following:

- auth0-spa-js: v1.13.6
- Tested in chrome, firefox, safari
- React.js, 17.0.1
- React-router-dom, 5.2.0

**Comment by frederikprijck** [comment]
Hi @mmykhaylov ,

It looks like there is an issue with the reproduction sample

```
const Kenobi = <p>General Kenobi!</p>;
const ProtectedKenobi = withAuthenticationRequired(Kenobi);
```

I guess you know this, and this is probably just an issue while preparing the reproduction sample. However, this needs to be changed first in order to proceed:

```
const Kenobi = () => <p>General Kenobi!</p>;
const ProtectedKenobi = withAuthenticationRequired(Kenobi);
```

Next, it looks like you are using `history: ^5.0.0` and `react-router-dom: ^5.2.0`.
The [docs for History](https://github.com/ReactTraining/history) mention:

> Documentation for version 5 can be found in the docs directory. This is the current stable release. Version 5 is used in React Router version 6.

Once I downgrade `history` to use version `4`, which is the version used in `react-router-dom` v5, it works as expected. 

https://www.loom.com/share/7f5a7afe2677432587cd0a5088e6c695

For future reference, the React SDK is located at https://github.com/auth0/auth0-react, which is a better place to report these kind of things.
