### ISSUE TITLE
Cannot read user subscriptions from twitch using the Auth0 for vuejs

### ISSUE THREAD

**Issue by hristopetroff** [auth0/auth0-spa-js#748]
I have an issues with the Auth0 twitch authentication. I am not able to read user subscriptions. After searching and searching in their documentation, i went in conclusion that the code should be like this
this.auth0Client = await createAuth0Client({
        domain: options.domain,
        client_id: options.clientId,
        audience: options.audience,
        redirect_uri: redirectUri,
        scope: 'email profile user:read:subscriptions' // change the scopes that are applied to every authz request. **Note**: `openid` is always specified regardless of this setting
      });
But even with this code, when Auth0 redirects me to the authorize page of twitch, twitch is saying that it will only read my email.

I will be happy is some manage to help me.
Thanks in advance.

**Comment by stevehobbsdev** [comment]
Hi @hristopetroff,

The `scope` option here is for Auth0's authorization API and is not passed along to a third-party connection such as Twitch. However, you're able to do this by using a `connection_scope` parameter and specify the scopes you want to send to the actual connection, in this case Twitch.

So you configuration should look like:

```js
this.auth0Client = await createAuth0Client({
  domain: options.domain,
  client_id: options.clientId,
  audience: options.audience,
  redirect_uri: redirectUri,
  connection_scope: 'user:read:subscriptions'
});
```

`connection_scope` is not something that is part of this SDK's API but it works because we allow you to pass any arbitrary property to the authorization server. You can read more about [passing custom scopes here](https://auth0.com/docs/connections/adding-scopes-for-an-external-idp#2-pass-scopes-to-authorize-endpoint).

I understand that this situation can be a little confusing, but hopefully this helps.
