### ISSUE TITLE
Different scopes for different providers

### ISSUE THREAD

**Issue by patrickcorrigan** [auth0/auth0-spa-js#756]
Hi, I'm requesting scopes as described here https://github.com/auth0/auth0-spa-js/issues/647 and it works well. 

However, the scopes I require are different for different auth providers. 

For example, for google I need the scope

`connection_scope: "https://www.googleapis.com/auth/calendar.events"`

But for AD I need

`connection_scope: "https://graph.microsoft.com/Calendars.Read"`

I'm adding these to `loginWithPopup`

Is there any way I can have different scopes when calling different providers

**Comment by stevehobbsdev** [comment]
Hi @patrickcorrigan,

This issue is really to do with Auth0 Server I'm afraid. This SDK does nothing to process `connection_scope` at all and simply passes it along in the request to the Universal Login Page.

I would encourage you to raise this in our [Auth0 Community forums](https://community.auth0.com) to see if you can get help from one of our experts there. Also have you tried just passing both scopes though, separated by spaces? I wonder if Google and AD would just ignore each other's scopes.

Closing for now but happy to continue the discussion.
