### ISSUE TITLE
The operation is insecure

### ISSUE THREAD

**Issue by flunderpero** [auth0/auth0-spa-js#805]
### Describe the problem

Some customers of ours report the error above. It seems to happen when trying to remove things from SessionStorage.

Would it be possible to make the use of SessionStorage optional, i.e. surround each call to it with a try / catch and ignore errors?

### Reproduction

We cannot reproduce this error, it just happen in production from time to time.

### Environment

- **Version of `auth0-spa-js` used:** 1.13.6
- **Which browsers have you tested in?** The error only happens in production (quite rarely), a sample user-agent is `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Safari/605.1.15`

**Comment by stevehobbsdev** [comment]
If you are seeing issues related to session storage, it's to do with our internal transaction management that is used when logging in. You can switch to using cookies instead by setting `useCookiesForTransactions: true` in the SDK config ([docs](https://auth0.github.io/auth0-spa-js/interfaces/auth0clientoptions.html#usecookiesfortransactions)).

Is that something you're able to try and see if it resolves the issue?

On another note, while it's not needed for this, I would always recommend keeping up-to-date with the latest version of this SDK as we may deploy security fixes.

**Comment by flunderpero** [comment]
I will give cookies a try here after thoroughly going through the implications, thanks for the pointer.

**Comment by stevehobbsdev** [comment]
No worries. As your issue appears infrequently, I'll close this for now but if it turns out that there is more investigation to undertake, please reply here or raise a new issue and we'll take a look.

Thanks

**Comment by jlaasonen** [comment]
I have the same problem. Appears to happen consistently with Safari. I am using auth0-spa-js version 1.19.4. The cause is `sessionStorage.removeItem(key)` in `storage.ts` line 121: https://sentry.io/share/issue/dc8ca347149f445cb99a37478826eea5/

Using `useCookiesForTransactions: true` does not help. Unfortunately, I do not have a Mac and cannot debug further.

**Comment by Aaronius** [comment]
We also have the same issue. It's consistently reproducible in a Safari private window. The underlying problem is that even just checking the type of `sessionStorage`, as is being done in https://github.com/auth0/auth0-spa-js/blob/1390ff8c00790894978eb713a38deaac5ecfe235/src/storage.ts#L103, is enough for Safari to throw the error. The more bulletproof solution is to wrap `sessionStorage.getItem` (and other storage method calls) in a `try-catch`.

Can we re-open this issue?

**Comment by scarow** [comment]
We're seeing this issue as well (intermittently), specifically when users access the auth0 screen through the Instagram browser. It's a bit annoying as I can't repro it on my account, but users have been able to trigger it and report it.

Any progress on this?
