### ISSUE TITLE
Update token for local storage

### ISSUE THREAD

**Issue by triorcs** [auth0/auth0-spa-js#808]
### Describe the problem you'd like to have solved

After users sign up, we would like to skip login process and auto log them in.

### Describe the ideal solution

Our backend will login user in via the auth0 api and return the access token, id token, refresh token to FE.
Now, if the package can provide a function to add/update these information above into local storage that will be perfact.

## Alternatives and current work-arounds

Due to package doesn't provide an interface to save the tokens above, we currently generate the session info by code and store into local storage with the same store name as auth0 doing via login page, which is risky if this package change the store name or login info which saved in the storage.

**Comment by frederikprijck** [comment]
Hey @triorcs ,

Can you elaborate a bit on your situation? What are you using this SDK for ?

You are saying your backend will call Auth0 to log the user in, the Auth0-SPA-JS SDK is designed to call Auth0 from the frontend.
When doing so, our SDK will be responsible for retrieving as well as storing the tokens.

When you get the tokens from your backend and send them to the frontend, there is little use in using our SDK and you might wanna handle the token storage and usage yourself.

**Comment by triorcs** [comment]
Hey @frederikprijck ,

We are using SDK to login user via loginWithRedirect and check user token status through getTokenSilently for FE.

And we have another follow for user sign up. once user signed up, rather than asking them login through login follow, we would like backend to login user in after create user. 
So now the backend calling auth0 nuget package received user login token and return to FE as part of response.
And if SDK and provide a function to store the response which contain access token, id token, refresh token into local storage that will be perfect and pretty useful.

**Comment by stevehobbsdev** [comment]
Hi @triorcs,

We don't plan to add the facility to accept tokens from outside, as the SDK is designed to do all this work for you. If you want to manage all this yourself, then as @frederikprijck mentioned there's little point in using this SDK. You may be better off using [Auth0.js](https://github.com/auth0/auth0.js) where there is no token management, and it is totally up to you as to how that works and where they are stored.

We _may_ in the future support the notion of calling some kind of `/token` endpoint on the same origin to facilitate scenarios where the backend holds these tokens, but we're not there yet.

As you say, you're able to update these tokens yourself in local storage but I would not recommend it, as we may change that without warning. However, the risk is yours to bear. You may also like to fork the library and add the functionality you need.

Closing for now, but happy to discuss further.

**Comment by gallivantor** [comment]
@stevehobbsdev  the scenario here is that we want the SDK to do all the work for us, and it is doing that just fine for logging in existing users and maintaining their tokens.

HOWEVER, we cannot use Auth0's built-in Signup flow for new users due to business requirements so we have our own custom signup flow, all we want to do is integrate our custom signup flow with the SDK so that once a new user signs up, we can hand over to the SDK to manage their login.

Currently the only way to do this without hacky code, is to redirect them to the Auth0 login page after they sign up, but that is a poor user experience as they have to enter their password twice - once to create the account, then again on the login page to sign in.

Therefore all we're looking for is the ability to say to the SDK - "hey, we just created this new user, here's their initial set of tokens, you take it from here". This scenario seems like something that other clients would have come across?

**Comment by julianwilkinson** [comment]
+1 for this, web views in app would benefit greatly from this flow.
