### ISSUE TITLE
Malformed access_token when not specifying audience

### ISSUE THREAD

**Issue by RichGuk** [auth0/auth0-spa-js#822]
I'm unsure if this is a misconfiguration within my tenant, an actual problem, or just some information missing from the docs. I may just not be understanding how OAuth works.

I'm using the `Auth0Client` and `getTokenSilently()`. I followed [these docs](https://auth0.com/docs/libraries/auth0-single-page-app-sdk) and did something like this:

```javascript
const auth0 = new Auth0Client({
  domain: DOMAIN,
  client_id: CLIENT_ID,
  cacheLocation: 'localstorage',
})

  const fetchUser = async () => {
    const query = window.location.search
    if (query.includes('code=') && query.includes('state=')) {
      const token = await auth0.getTokenSilently()
      setToken(token)

      window.history.replaceState({}, document.title, '/')
    } else {
      try {
        const token = await auth0.getTokenSilently()
        setToken(token)
      } catch (error) {
        if (error.error === 'login_required') {
          await auth0.loginWithRedirect()
          return
        }

        throw error
      }
    }

    const user = await auth0.getUser()
    setUser(user)
  }
  ```
The docs mention nothing about adding `audience` to either the constructor or the call to `getTokenSilently()` (although I noticed the example for `getTokenWithPopup` does mention audience). Without it, I get a malformed token:

```ZXUuYXV0aDAuY29tLyJ9..pnqr8CrOTArbQ8a4.Z3Db2WmYMtF2S```

(note the two repeating dots)

I get a valid token if I add the audience to either the constructor or the getTokenSilently() call. 

The settings tab for my tenant:

![image](https://user-images.githubusercontent.com/12284/137752899-6320fcc1-a744-4658-942c-06ec8fb5ff86.png)

Am I simply misunderstanding something?

**Comment by robbytx** [comment]
I'm glad I found this!  I've reviewed lots of Auth0 documentation over past several days and nowhere until here did I figure out that passing the audience was necessary to get a valid access token for my API.  I even looked at the very page referenced above, but I saw only the statement:
> Access tokens issued for the Management API and access tokens issued for any custom API that you have registered with Auth0 follow the JWT standard, ...

Which made me think something was simply wrong, since the access token I was getting for my SPA was not following the standard.

Among the other places I looked for this information:

* The "Quick Start" in the Auth0 dashboard for my SPA application
* The [documentation for this SDK](https://auth0.com/docs/libraries/auth0-single-page-app-sdk)
* The [API + SPA configuration](https://auth0.com/docs/get-started/architecture-scenarios/spa-api/part-3)

Admittedly, the "audience" property is visible on this last item, but I did not realize its importance until now, and its example uses the `auth0.js` library directly so I wasn't paying close attention to the specifics.  

It would have been a huge help if the documentation for this SDK included an example of passing "audience" in the client configuration.  As it stands the only mention of "audience" on that page is in the example to trying to get an access token for a difference audience, but with the disclaimer that this doesn't work with refresh token rotation, which I am using.
