### ISSUE TITLE
After successful user sign-in, Auth0Client.isAuthenticated() returns as false when refresh the page(With MFA enabled)

### ISSUE THREAD

**Issue by NiroshanP** [auth0/auth0-spa-js#828]
After successfully sign-in in to the site, When the user refreshes the page (by clicking F5), auth0Client.isAuthenticated() returns false. This issue observes when MFA is enabled. When MFA is disabled, the user gets isAuthenticated() as true when refreshing the page.

If the user is already sign-in, regardless of MFA enable/disabled user should get the appropriate authentication status. In this case, it should be true. 

Appreciate your support on this.

Version of `auth0-spa-js` used: 1.19
- Browsers have you tested: Chrome

**Comment by stevehobbsdev** [comment]
Thanks for your patience here @NiroshanP. I've had a look into this and unfortunately the behaviour you're seeing is expected. We're kind of at the whim of the server here so, directly relating to this SDK there's not too much we can do (but read on).

By default the SDK performs silent auth by using an iframe and the `response_mode=web_message` flow, which relies on the user's Auth0 session. It's essentially doing a proper login step but unattended, meaning the user doesn't get a chance to interact. If the server decides it needs to interact with the user to complete the MFA step, it throws an error during silent auth as there is no interaction.

If the user was to tick the box that says "Remember me for 30 days" then silent auth on page reload will work fine, but I think this depends on what method of MFA you're using (I tested all this using One-Time Password). The issue here is that the user does not get shown this checkbox when they're enrolling in MFA for the first time - only on subsequent logins. I'm going to raise that with the relevant team internally.

Please have a read of [this MFA article](https://auth0.com/docs/login/mfa/customize-mfa-user-pages#change-authentication-request-frequency) that shows how to configure MFA to be asked less frequently using a custom Rule.

Another option that you can do on the SDK side is to configure your app to use refresh tokens + local storage (or use a custom, persistent secure storage for tokens), but please be aware that this [changes the security profile of your app](https://auth0.com/docs/libraries/auth0-single-page-app-sdk#change-storage-options) so you should be aware of the implications.

I'm drafting up some info around this for our FAQ in case this question comes up again.

**Comment by NiroshanP** [comment]
Thanks for the update @stevehobbsdev, We were able to overcome this issue by adding MFA with rules. we do bypass the MFA by adding the following logic to the rule. can't we allow a similar kind of thing as an optional param to SDK ? 

if (context.request.query.prompt !== 'none' )

**Comment by stevehobbsdev** [comment]
Unless I misunderstood the question, you are already able to pass through custom parameters for the purpose of picking them up in a Rule and performing some custom logic. Does this help?

**Comment by NiroshanP** [comment]
Actually what I meant is, instead of using the following logic in the rule, can we have the same option in the SDK by passing some param. (e.g. option='none')

if (context.request.query.prompt !== 'none' )
