### ISSUE TITLE
Usage of fast-text-encoding causes potential encoding issues

### ISSUE THREAD

**Issue by nader-fl** [auth0/auth0-spa-js#853]
### Describe the problem you'd like to have solved

fast-text-encoding dependency does not support UTF encodings outside UTF-8, which causes potential problems with more modern dependencies or code that uses more modern encodings. The particular dependencies I've had run into the issue is @react-pdf/renderer, which needs UTF-16le, which is supported by major browsers but not by fast-text-encoding.

### Describe the ideal solution

Update the fast-text-encoding dep to a different lib that supports encodings more in line with modern browsers.

## Alternatives and current work-arounds

Forcing UTF-8 encoding within the dependency code (@react-pdf/renderer in this case), fixes the issue, but custom code in dependencies is not ideal. Changing dependency code or source code to use an older encoding is also not ideal.

**Comment by nader-fl** [comment]
I have attempted a simple fix: removing the fast-encoding dep from this project is enough to fix the issue (by defaulting to the node-provided text encoder)

this should be submitted asap as it's a trivial change and inconsequential from what I can tell

**Comment by stevehobbsdev** [comment]
Thanks for raising this @nader-fl. In this library, the only place we do text encoding is for the generation of SHA-256 strings, but I'm assuming that because it's a polyfill it's affecting other areas of your own app?

Is it not also the case that the [polyfill will defer to the native implementation](https://github.com/samthor/fast-text-encoding/blob/master/text.js#L27-L29) if one is available?

The challenges here are:

* Right now we still have a need to support browsers that require use of this polyfill
* We are optimizing for browser environments and not node - is there where you're using this?

The first point is definitely something we want to solve for in the future, but it's not going to happen too quickly. Just trying to understand the impact above.

**Comment by nader-fl** [comment]
I appreciate the response @stevehobbsdev !

I had not considered the implementation on multiple browsers! You are correct that I am running this in node. This problem does not happen within my browser, it only occurs within my node test harness. The problem being that the text encoder lib seems to share the name of the native text encoder, which ends up being used by other parts of the app, within the test.

In the end, I ended up mocking the service that was attempting to text encode, which meant having to test the mocked service separately. The other workaround was to delete the text-encoder import from the spa-js lib, but that wasn't a great solution since we couldn't reproduce in our CI environment.

No matter how you guys address this, thanks again for the time taken to respond!

**Comment by stevehobbsdev** [comment]
Thanks @nader-fl. The primary use case of this SDK is in the browser so that's what we optimise for. We're looking at options as to how to provide a build that doesn't include all these polyfills but we're not quite there yet. Until then, although it's not ideal, your mocking solution sounds reasonable for the meantime.

**Comment by afroneth** [comment]
@nader-fl 

Hi, I am facing the same issue while using @react-pdf/renderer. Could you share with me how to set up the mocking service for text encoding/decoding? I am currently failing my jest tests with this error:

`RangeError: Failed to construct 'TextDecoder': The encoding label provided ('utf-16le') is invalid.`

Thank you!

> I appreciate the response @stevehobbsdev !
> 
> I had not considered the implementation on multiple browsers! You are correct that I am running this in node. This problem does not happen within my browser, it only occurs within my node test harness. The problem being that the text encoder lib seems to share the name of the native text encoder, which ends up being used by other parts of the app, within the test.
> 
> In the end, I ended up mocking the service that was attempting to text encode, which meant having to test the mocked service separately. The other workaround was to delete the text-encoder import from the spa-js lib, but that wasn't a great solution since we couldn't reproduce in our CI environment.
> 
> No matter how you guys address this, thanks again for the time taken to respond!
