### ISSUE TITLE
Auth0Client.getTokenSilently does not handle undefined audience.

### ISSUE THREAD

**Issue by fullstackfool** [auth0/auth0-spa-js#880]
### Describe the problem
When calling `getTokenSilently({audience: undefined})` the returned token is invalid.

### What was the expected behavior?

`getTokenSilently({audience: undefined})` should behave the same as `getTokenSilently()` and utilise the globally configured `audience`.

### Reproduction

**Can the behavior be reproduced using the [SPA SDK Playground](https://github.com/auth0/auth0-spa-js/blob/master/DEVELOPMENT.md#the-sdk-playground)?**
Having issue replicating this in the playground as I am not aware of the available audiences.

### Environment

- **Version of `auth0-spa-js` used:** 1.20.0
- **Which browsers have you tested in?** Firefox/Chrome
- **Which framework are you using, if applicable (Angular, React, etc):** Vue
- **Other modules/plugins/libraries that might be involved:** N/A

**Comment by stevehobbsdev** [comment]
Thanks for the report here. What's the use case for sending through `audience: undefined`, or is this simply a behaviour problem you've noticed? Also:

> the returned token is invalid

Can you elaborate? Invalid how?

**Comment by fullstackfool** [comment]
> Thanks for the report here. What's the use case for sending through audience: undefined, or is this simply a behaviour problem you've noticed?

Mostly just strange behavior, noticed when calling the function with a local configuration option that may have an empty `audience` key, for instance:
```js
        return client.getTokenSilently({
            ignoreCache: options?.ignoreCache,
            scope: options?.scope,
            audience: options?.audience,
            timeoutInSeconds: options?.timeout
        });
```


> the returned token is invalid
> > Can you elaborate? Invalid how?
A token is returned, but it is malformed. 

<img width="597" alt="image" src="https://user-images.githubusercontent.com/14146557/156379840-62ba82bb-b8eb-495f-94ff-ec30b7db2cd2.png">

(Also, thank you for answering so quickly!)

**Comment by fullstackfool** [comment]
Right, I think see. So the `default` refers to this setting in the dashboard? Given it is blank that would explain the malformed token that is returned. If I set it then a valid token is generated.

<img width="560" alt="Screenshot 2022-03-02 at 16 28 32" src="https://user-images.githubusercontent.com/14146557/156404513-8581529d-ecd7-4c7b-9312-3edc9fd6f8c9.png">

This does not explain, however, why there is a difference in behaviour between `getTokenSilently({audience: undefined})` and `getTokenSilently()`

**Comment by stevehobbsdev** [comment]
Thanks for your patience here @fullstackfool and apologies that I didn't get a response to you in time before raising the PR. I think @frederikprijck's [answer here](https://github.com/auth0/auth0-spa-js/pull/881#discussion_r819369691) explains the situation but happy to continue the conversation if you have further questions.

> So the default refers to this setting in the dashboard?

I suppose you could look at it that way; we use `default` inside the SDK for our token caching just when it hasn't been configured with an audience, which ultimately means that no value for `audience` will be sent to Auth0. However, if your Auth0 tenant has been configured with a default audience then yes, that's the audience that will be used.

It the vast majority of cases though, you usually want to send an `audience` value from the SDK rather than rely on the default tenant setting, it'll just give you less problems over time.

> A token is returned, but it is malformed.

This comes up a lot so you're not alone. What's actually happening is that by providing an audience, Auth0 will return an Access Token in JWT format, which can be parsed and validated by a [resource server](https://www.oauth.com/oauth2-servers/the-resource-server/). When **not** specifying an audience, an opaque token is returned which of course can't be parsed by anything.

If you're interested, here's some [further reading on Auth0 Access Tokens](https://auth0.com/docs/secure/tokens/access-tokens) in case you hadn't come across it.

**Comment by fullstackfool** [comment]
> Thanks for your patience here @fullstackfool and apologies that I didn't get a response to you in time before raising the PR.

No worries! Thank you for the review and feedback.
 
Ultimately I think we agree that the current behavior is a little unexpected, but is an edgecase that is too costly to fix right now.

**Comment by bribar** [comment]
Hi @fullstackfool @stevehobbsdev,
I have a similar issue... 

https://stackoverflow.com/questions/71713845/auth0-the-jwt-string-must-contain-two-dots

...where the token is invalid using jwt.io and server side gives throws exception using Auth0 PHP SDK.

I tried using audience: undefined in createAuth0Client and getTokenSilently() but still produces an invalid token.

Any thoughts on my issue?
