### ISSUE TITLE
getTokenSilently fails, getTokenWIthPopup falls back successfully but user/isAuthenticated gets reset

### ISSUE THREAD

**Issue by purepear** [auth0/auth0-spa-js#895]
### Describe the problem

Hi guys, i'm using `@auth0/auth0-vue` but i believe the issue(if it is an actual issue) originates in `@auth0/auth0-spa-js`.
I'm testing in Chrome Incognito with third-party cookies disabled. I can successfully login. At some point i need to get an access token based on audience & scope so i use `getAccessTokenSilently` but because the cookies are not sent, this fails. And so i decided to fallback to `getAccessTokenWithPopup`. This gets me the token but after the failed `getAccessTokenSilently` request, auth0 is "resetting" the `user` and `isAuthenticated` is false.

### What was the expected behavior?

Given that the user just logged in, and even though `getTokenSilently` failed, `getTokenWithPopup` succeeded but `isAuthenticated` is still false. 
I was expecting `isAuthenticated` to be true because i did get a proper access token at the end.

### Reproduction
Before creating a repro, i just want to confirm that this is actually a bug and not the expected behaviour (because i have some doubts 😄). Here is a simplified example:

```js 
async function getAccessToken() {
  const options = { audience: 'abcd', scope: 'efgh' }
  
  let token 
  
  try {
    await auth.isAuthenticated() // true
    await auth.getUser() // user 
    
    token = await auth.getTokenSilently(options) // throws 'login_required' error because third-party cookies are disabled
  } catch(e) {
    await auth.isAuthenticated() // false
    await auth.getUser() // no user
    
    token = await auth.getTokenWithPopup(options) // access token works
    
    await auth.isAuthenticated() // still false
    await auth.getUser() // still no user
  }
  
  return token
}
```

**Can the behavior be reproduced using the [SPA SDK Playground](https://github.com/auth0/auth0-spa-js/blob/master/DEVELOPMENT.md#the-sdk-playground)?**

### Environment

- **Version of `auth0-spa-js` used:** 1.20.1
- **Which browsers have you tested in?** Chrome 100 - Incognito window
- **Which framework are you using, if applicable (Angular, React, etc):** Vue
- **Other modules/plugins/libraries that might be involved:** `@auth0/auth0-vue@1.0.0`

**Comment by frederikprijck** [comment]
Hey,

I believe what you are seeing is expected. If no token is available, `getTokenSilently` will try and get a token. 

Let met explain a scenario that could match with what you have (but please do correct me if that assumption is wrong):

- The Vue plugin is configured using the default scope (so its omitted) or by setting scope to a specific set of scopes `scope1 scope2`, without setting an audience or by setting the audience to `audience1`.
- `loginWithRedirect` is called, which uses the above-configured scope and audience when non provided here
- The user is eventually logged in, a token is retrieved and stored in our cache using the above configured audience and scope,
- `getTokenSilently` is called, providing an audience and/or scope that is different from the above.
  important here is that it can't find a match in our cache because the audience and/or scope is different. If you would have configured the SDK to use Refresh Tokens, it wont be able to find one (because the initially retrieved set of tokens is for a different scope and audience, so we shouldnt use the one from the cache) and rely on the iframe fallback that needs 3rd party cookies.

A way to solve this is to use Refresh Tokens, as well as ensuring you provide the same audience and scope to `getTokenSilently` as you provide when registering the Vue plugin in this case (note, scope in the Vue plugin needs to include the scopes from `getTokenSilently`, but it may include more as well, just not less). 

Doing so will ensure that when you call `loginWithRedirect`, it will result in issuing a Refresh Token that then will be used when calling `getTokenSIlently` because it can retrieve it from the cache.

Note however that can still be a situation where a call to `/authorize` is made when calling `getTokenSIlently`, which relies on third party cookies. An example here is when the refresh token is expired. In that case you need to either catch the error and call `loginWithRedirect` again, or configure auth0 to use a custom domain. If the domain for auth0 matches your app's domain you are not relying on third party cookies anymore.

Let me know if this doesn't make sense, this is also explained in https://github.com/auth0/auth0-vue/blob/main/FAQ.md#1-user-is-not-logged-in-after-page-refresh

**Comment by frederikprijck** [comment]
Regarding the user not being logged in, it seems that, when calling `getTokenSilently` will call `logout` when `login_required` is thrown: https://github.com/auth0/auth0-spa-js/blob/master/src/Auth0Client.ts#L1156 (this could be resolved by what is mentioned in my previous comment).

If you call `getTokenWithPopup` with an audience or scope different from the global scope, you need to provide the same audience and / or scope to `getUser` and `isAuthenticated`, which I believe is a bit weird but is the consequence of not using all the scopes and the same audience in when registering the Vue Plugin .

**Comment by purepear** [comment]
Thank you for your informative response @frederikprijck!
Everything you shared makes sense, it's just that our use case is a bit weird :)

Your assumptions are correct:
* User logs in with default scope(no scope provided) and no audience. `loginWithRedirect` works - all good.
* User selects which "API" they're going to use. This calls `getTokenSilently` with the selected API's audience and scope. I hear your advice to use single audience with different scopes but unfortunately this is not how our setup works at the moment (and not really an option for the foreseeable future).

We are in the process of switching to Custom Domains but there're also different deploy preview domains and as you said - localhost (for local development) to be considered... so i'm working with "disabled 3rd party cookies" in mind.

That said, the "disabled 3rd party cookies" support is not really needed for real use cases but mostly for short testing cases(no long sessions expected) so i'm currently thinking of 2 ways to "circumvent" the undesired logout after unsuccessful call to `getTokenSilently`:
* If there's an easy way to detect whether 3rd party cookies are enabled and if they are we will use `getTokenSilently`, otherwise we will use `getTokenWIthPopup` to get the token
* wrap `getTokenSilently` in try catch and display a hard stop error text that asks the user to allow 3rd party cookies.

Interested if you have some other suggestions given the limitations we face 🤔 And thanks again for you helpful input.

**Comment by frederikprijck** [comment]
When `getTokenSilently` fails and throws `login_required`, you can also call `loginWithRedirect` again with the audience based on the API selected. That way you get an initial set of tokens for that audience using the interactive approach, not relying on 3rd party cookies. You still need to ensure the scopes are all included tho.

This should also be required if your API requires consent from the user before being able to call it, which you can't do in a non-interactive flow (geTikenSilently). 

As the user is already logged in, they shouldn't be asked for credentials on the Auth0 side, and if no consent is needed, they should instantly end up in your application.

It's not ideal, but if you guard this behavior with first trying `getTokenSilently` and only do the redirect when you get `login_required`, it should only kick in for users that either still need consent (who need to go through the interactive flow anyway) or users that have 3rd party cookies blocked.

**Comment by purepear** [comment]
> When getTokenSilently fails and throws login_required, you can also call loginWithRedirect again with the audience based on the API selected. That way you get an initial set of tokens for that audience using the interactive approach, not relying on 3rd party cookies. You still need to ensure the scopes are all included tho.

I actually tried this earlier but ended up in and infinite redirect loop, and so i thought it's not supposed to work like that, but i'll give it another go :)

**Comment by frederikprijck** [comment]
> I actually tried this earlier but ended up in and infinite redirect loop, and so i thought it's not supposed to work like that, but i'll give it another go :)

Thinking about this some more, I can see there might be an issue here when you first hit `getTokenSilently` which throws `login_required`, which logs you out, including the default audience and scope (before selecting an API). When u now call loginWithRedirect with the audience and scope for the selected API, you get tokens for the new audience and scope but you don't have any tokens for the default audience anymore. The SDK would consider you not authenticated.

Something that I can see working would be a situation where you actually store the selected API (e.g. in the browser's session storage), and use it on page load to use as the default audience and scope when configuring the Vue plugin. Essentially acting as some kind of mechanism where a user logs in to the platform in the context of a specific API. 

```
const { audience, scope } = getAudienceAndScopeFromSessionStorage();
app.use(
  createAuth0({
    audience: audience || null,
    scope: audience || null
  })
);
```

Now whenever a user selects a new API, you should be able to:

- store the API / audience / scope in session storage
- call `loginWithRedirect` with the new audience and scope if `getTokenSilently` threw `login_required`

I think you can't do a `getTokenSilently` in between selecting  an API and calling `loginWithRedirect`, because if that would succeed, your current selected API's audience and scope are not set as the Vue Plugins global `audience` and `scope`, and you might get weird behavior when calling things like `getUser()` without specifying the `audience` and `scope`.

Not ideal, but I believe working around 3rd party cookies is definitely not easy if you can't have custom domains.

Anyway, if you would have some kind of example repository that demonstrates what you are trying and what isn't working, I am more than happy to give it a look!

**Comment by stevehobbsdev** [comment]
I'll close this for now as it looks to have been answered, but please feel free to continue the conversation if need be.
