### ISSUE TITLE
Allow Auth0 to be tested over local network

### ISSUE THREAD

**Issue by programmingninjas** [auth0/auth0-spa-js#924]
### Problem

Whenever I develop a react app I check it on my android mobile too using IP address that react has hosted this app on. But after using Auth0  react app goes blank. This is happening because auth0-spa-js must run on a secure origin and react is using http + ip address which is not allowed by auth0.

**Comment by stevehobbsdev** [comment]
Unfortunately this is not something we artificial limit; this is instead limited by the fact that we rely on the browser's native crypto API being available, which requires the app to be running on a secure origin.

Recommendation here is to configure your React app so that it can use HTTPS even in your local environment. Using something like [Caddy](https://caddyserver.com/docs/quick-starts/https) might be one option that could help here.
